/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Như Tâm
 */
public class CreateReturnOrder_GUI extends javax.swing.JPanel {

    /**
     * Creates new form CreateReturnOrder_GUI
     */
    public CreateReturnOrder_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_returnOrder = new javax.swing.ButtonGroup();
        spl_createReturnOrder = new javax.swing.JSplitPane();
        pnl_order = new javax.swing.JPanel();
        pnl_searchOrder = new javax.swing.JPanel();
        txt_searchOrder = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 10), new java.awt.Dimension(32767, 0));
        pnl_buttonSearchOrder = new javax.swing.JPanel();
        btn_searchOrder = new javax.swing.JButton();
        pnl_orderInfor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnl_right = new javax.swing.JPanel();
        pnl_returnOrder = new javax.swing.JPanel();
        pnl_employeeInfor = new javax.swing.JPanel();
        pnl_employeeID = new javax.swing.JPanel();
        lbl_employeeID = new javax.swing.JLabel();
        txt_employeeID = new javax.swing.JTextField();
        pnl_nameEmp = new javax.swing.JPanel();
        lbl_nameEmp = new javax.swing.JLabel();
        txt_nameEmp = new javax.swing.JTextField();
        pnl_returnOrderInfor = new javax.swing.JPanel();
        pnl_returnOrderID = new javax.swing.JPanel();
        lbl_returnOrderID = new javax.swing.JLabel();
        txt_returnOrderID = new javax.swing.JTextField();
        pnl_returnOrderDate = new javax.swing.JPanel();
        lbl_returnOrderDate = new javax.swing.JLabel();
        txt_returnOrderDate = new javax.swing.JTextField();
        pnl_productReturn = new javax.swing.JPanel();
        pnl_lblProduct = new javax.swing.JPanel();
        lbl_product = new javax.swing.JLabel();
        src_tblProduct = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        pnl_typeReturnOrder = new javax.swing.JPanel();
        lbl_typeReturnOrder = new javax.swing.JLabel();
        pnl_buttonTypeReturnOrder = new javax.swing.JPanel();
        rdb_exchange = new javax.swing.JRadioButton();
        rdb_return = new javax.swing.JRadioButton();
        pnl_descreptionReturnOrder = new javax.swing.JPanel();
        lbl_descreptionReturnOrder = new javax.swing.JLabel();
        txt_descreptionReturnOrder = new javax.swing.JTextField();
        pnl_createReturnOrder = new javax.swing.JPanel();
        btn_createReturnOrder = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        spl_createReturnOrder.setResizeWeight(0.95);

        pnl_order.setMinimumSize(new java.awt.Dimension(500, 123));
        pnl_order.setPreferredSize(new java.awt.Dimension(700, 768));
        pnl_order.setLayout(new java.awt.BorderLayout());

        pnl_searchOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        pnl_searchOrder.setMinimumSize(new java.awt.Dimension(457, 37));
        pnl_searchOrder.setLayout(new javax.swing.BoxLayout(pnl_searchOrder, javax.swing.BoxLayout.X_AXIS));

        txt_searchOrder.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã hoá đơn");
        pnl_searchOrder.add(txt_searchOrder);
        pnl_searchOrder.add(filler1);

        pnl_buttonSearchOrder.setMaximumSize(new java.awt.Dimension(50, 2147483647));
        pnl_buttonSearchOrder.setLayout(new java.awt.BorderLayout());

        btn_searchOrder.setText("Tìm kiếm");
        btn_searchOrder.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        pnl_buttonSearchOrder.add(btn_searchOrder, java.awt.BorderLayout.CENTER);

        pnl_searchOrder.add(pnl_buttonSearchOrder);

        pnl_order.add(pnl_searchOrder, java.awt.BorderLayout.NORTH);

        pnl_orderInfor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hoá đơn"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_orderInfor.setPreferredSize(new java.awt.Dimension(150, 700));
        pnl_orderInfor.setLayout(new java.awt.BorderLayout(0, 10));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Mã KH", "Ngày mua", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pnl_orderInfor.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "SL", "Đơn giá", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        pnl_orderInfor.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_order.add(pnl_orderInfor, java.awt.BorderLayout.CENTER);

        spl_createReturnOrder.setLeftComponent(pnl_order);

        pnl_right.setMaximumSize(new java.awt.Dimension(600, 2147483647));
        pnl_right.setMinimumSize(new java.awt.Dimension(500, 123));
        pnl_right.setLayout(new java.awt.BorderLayout());

        pnl_returnOrder.setMaximumSize(new java.awt.Dimension(600, 768));
        pnl_returnOrder.setMinimumSize(new java.awt.Dimension(400, 123));
        pnl_returnOrder.setPreferredSize(new java.awt.Dimension(400, 768));
        pnl_returnOrder.setLayout(new javax.swing.BoxLayout(pnl_returnOrder, javax.swing.BoxLayout.Y_AXIS));

        pnl_employeeInfor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Nhân viên"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_employeeInfor.setMinimumSize(new java.awt.Dimension(400, 113));
        pnl_employeeInfor.setPreferredSize(new java.awt.Dimension(30, 100));
        pnl_employeeInfor.setLayout(new javax.swing.BoxLayout(pnl_employeeInfor, javax.swing.BoxLayout.Y_AXIS));

        pnl_employeeID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_employeeID.setLayout(new javax.swing.BoxLayout(pnl_employeeID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_employeeID.setText("Mã nhân viên:");
        pnl_employeeID.add(lbl_employeeID);

        txt_employeeID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_employeeID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_employeeID.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_employeeID.add(txt_employeeID);

        pnl_employeeInfor.add(pnl_employeeID);

        pnl_nameEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_nameEmp.setLayout(new javax.swing.BoxLayout(pnl_nameEmp, javax.swing.BoxLayout.X_AXIS));

        lbl_nameEmp.setText("Tên nhân viên:");
        pnl_nameEmp.add(lbl_nameEmp);

        txt_nameEmp.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_nameEmp.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_nameEmp.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_nameEmp.add(txt_nameEmp);

        pnl_employeeInfor.add(pnl_nameEmp);

        pnl_returnOrder.add(pnl_employeeInfor);

        pnl_returnOrderInfor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đơn đổi trả"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_returnOrderInfor.setMinimumSize(new java.awt.Dimension(400, 278));
        pnl_returnOrderInfor.setPreferredSize(new java.awt.Dimension(400, 100));
        pnl_returnOrderInfor.setLayout(new javax.swing.BoxLayout(pnl_returnOrderInfor, javax.swing.BoxLayout.Y_AXIS));

        pnl_returnOrderID.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pnl_returnOrderID.setMaximumSize(new java.awt.Dimension(2147483647, 45));
        pnl_returnOrderID.setMinimumSize(new java.awt.Dimension(118, 45));
        pnl_returnOrderID.setPreferredSize(new java.awt.Dimension(597, 34));
        pnl_returnOrderID.setLayout(new javax.swing.BoxLayout(pnl_returnOrderID, javax.swing.BoxLayout.X_AXIS));

        lbl_returnOrderID.setText("Mã HĐĐT:");
        lbl_returnOrderID.setMaximumSize(new java.awt.Dimension(85, 16));
        lbl_returnOrderID.setMinimumSize(new java.awt.Dimension(85, 16));
        lbl_returnOrderID.setPreferredSize(new java.awt.Dimension(85, 16));
        pnl_returnOrderID.add(lbl_returnOrderID);

        txt_returnOrderID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_returnOrderID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_returnOrderID.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_returnOrderID.add(txt_returnOrderID);

        pnl_returnOrderInfor.add(pnl_returnOrderID);

        pnl_returnOrderDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pnl_returnOrderDate.setMaximumSize(new java.awt.Dimension(2147483647, 45));
        pnl_returnOrderDate.setMinimumSize(new java.awt.Dimension(132, 45));
        pnl_returnOrderDate.setPreferredSize(new java.awt.Dimension(132, 50));
        pnl_returnOrderDate.setLayout(new javax.swing.BoxLayout(pnl_returnOrderDate, javax.swing.BoxLayout.X_AXIS));

        lbl_returnOrderDate.setText("Ngày đổi trả:");
        pnl_returnOrderDate.add(lbl_returnOrderDate);

        txt_returnOrderDate.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_returnOrderDate.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_returnOrderDate.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_returnOrderDate.add(txt_returnOrderDate);

        pnl_returnOrderInfor.add(pnl_returnOrderDate);

        pnl_productReturn.setLayout(new javax.swing.BoxLayout(pnl_productReturn, javax.swing.BoxLayout.Y_AXIS));

        pnl_lblProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_lblProduct.setMaximumSize(new java.awt.Dimension(2147483647, 34));
        pnl_lblProduct.setPreferredSize(new java.awt.Dimension(10, 34));
        pnl_lblProduct.setLayout(new java.awt.BorderLayout());

        lbl_product.setText("Sản phẩm");
        lbl_product.setMaximumSize(new java.awt.Dimension(53, 30));
        lbl_product.setMinimumSize(new java.awt.Dimension(53, 30));
        lbl_product.setPreferredSize(new java.awt.Dimension(53, 30));
        pnl_lblProduct.add(lbl_product, java.awt.BorderLayout.CENTER);

        pnl_productReturn.add(pnl_lblProduct);

        src_tblProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "SL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_product.setMinimumSize(new java.awt.Dimension(45, 60));
        src_tblProduct.setViewportView(tbl_product);
        if (tbl_product.getColumnModel().getColumnCount() > 0) {
            tbl_product.getColumnModel().getColumn(2).setResizable(false);
        }

        pnl_productReturn.add(src_tblProduct);

        pnl_returnOrderInfor.add(pnl_productReturn);

        pnl_typeReturnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pnl_typeReturnOrder.setMaximumSize(new java.awt.Dimension(32792, 34));
        pnl_typeReturnOrder.setPreferredSize(new java.awt.Dimension(1191, 34));
        pnl_typeReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_typeReturnOrder, javax.swing.BoxLayout.X_AXIS));

        lbl_typeReturnOrder.setText("Loại:");
        lbl_typeReturnOrder.setPreferredSize(lbl_returnOrderDate.getPreferredSize());
        pnl_typeReturnOrder.add(lbl_typeReturnOrder);

        pnl_buttonTypeReturnOrder.setMaximumSize(new java.awt.Dimension(32767, 30));
        pnl_buttonTypeReturnOrder.setMinimumSize(new java.awt.Dimension(155, 30));
        pnl_buttonTypeReturnOrder.setPreferredSize(new java.awt.Dimension(155, 30));
        pnl_buttonTypeReturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        group_returnOrder.add(rdb_exchange);
        rdb_exchange.setText("Đổi hàng");
        pnl_buttonTypeReturnOrder.add(rdb_exchange);

        group_returnOrder.add(rdb_return);
        rdb_return.setText("Trả hàng");
        pnl_buttonTypeReturnOrder.add(rdb_return);

        pnl_typeReturnOrder.add(pnl_buttonTypeReturnOrder);

        pnl_returnOrderInfor.add(pnl_typeReturnOrder);

        pnl_descreptionReturnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pnl_descreptionReturnOrder.setMaximumSize(new java.awt.Dimension(2147483647, 34));
        pnl_descreptionReturnOrder.setPreferredSize(new java.awt.Dimension(741, 34));
        pnl_descreptionReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_descreptionReturnOrder, javax.swing.BoxLayout.X_AXIS));

        lbl_descreptionReturnOrder.setText("Lý do:");
        lbl_descreptionReturnOrder.setPreferredSize(lbl_returnOrderDate.getPreferredSize());
        pnl_descreptionReturnOrder.add(lbl_descreptionReturnOrder);

        txt_descreptionReturnOrder.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_descreptionReturnOrder.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_descreptionReturnOrder.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_descreptionReturnOrder.add(txt_descreptionReturnOrder);

        pnl_returnOrderInfor.add(pnl_descreptionReturnOrder);

        pnl_createReturnOrder.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_createReturnOrder.setPreferredSize(new java.awt.Dimension(1191, 50));
        pnl_createReturnOrder.setLayout(new java.awt.BorderLayout());

        btn_createReturnOrder.setText("TẠO ĐƠN ĐỔI TRẢ");
        btn_createReturnOrder.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        pnl_createReturnOrder.add(btn_createReturnOrder, java.awt.BorderLayout.CENTER);

        pnl_returnOrderInfor.add(pnl_createReturnOrder);

        pnl_returnOrder.add(pnl_returnOrderInfor);

        pnl_right.add(pnl_returnOrder, java.awt.BorderLayout.CENTER);

        spl_createReturnOrder.setRightComponent(pnl_right);

        add(spl_createReturnOrder, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createReturnOrder;
    private javax.swing.JButton btn_searchOrder;
    private javax.swing.Box.Filler filler1;
    private javax.swing.ButtonGroup group_returnOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_descreptionReturnOrder;
    private javax.swing.JLabel lbl_employeeID;
    private javax.swing.JLabel lbl_nameEmp;
    private javax.swing.JLabel lbl_product;
    private javax.swing.JLabel lbl_returnOrderDate;
    private javax.swing.JLabel lbl_returnOrderID;
    private javax.swing.JLabel lbl_typeReturnOrder;
    private javax.swing.JPanel pnl_buttonSearchOrder;
    private javax.swing.JPanel pnl_buttonTypeReturnOrder;
    private javax.swing.JPanel pnl_createReturnOrder;
    private javax.swing.JPanel pnl_descreptionReturnOrder;
    private javax.swing.JPanel pnl_employeeID;
    private javax.swing.JPanel pnl_employeeInfor;
    private javax.swing.JPanel pnl_lblProduct;
    private javax.swing.JPanel pnl_nameEmp;
    private javax.swing.JPanel pnl_order;
    private javax.swing.JPanel pnl_orderInfor;
    private javax.swing.JPanel pnl_productReturn;
    private javax.swing.JPanel pnl_returnOrder;
    private javax.swing.JPanel pnl_returnOrderDate;
    private javax.swing.JPanel pnl_returnOrderID;
    private javax.swing.JPanel pnl_returnOrderInfor;
    private javax.swing.JPanel pnl_right;
    private javax.swing.JPanel pnl_searchOrder;
    private javax.swing.JPanel pnl_typeReturnOrder;
    private javax.swing.JRadioButton rdb_exchange;
    private javax.swing.JRadioButton rdb_return;
    private javax.swing.JSplitPane spl_createReturnOrder;
    private javax.swing.JScrollPane src_tblProduct;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_descreptionReturnOrder;
    private javax.swing.JTextField txt_employeeID;
    private javax.swing.JTextField txt_nameEmp;
    private javax.swing.JTextField txt_returnOrderDate;
    private javax.swing.JTextField txt_returnOrderID;
    private javax.swing.JTextField txt_searchOrder;
    // End of variables declaration//GEN-END:variables
}
