/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Hoàng Khang
 */
public class CustomerManagement_GUI extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManagement_GUI
     */
    public CustomerManagement_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_gender = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_info = new javax.swing.JPanel();
        pnl_infoBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_id1 = new javax.swing.JLabel();
        txt_id1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_id2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        lbl_id3 = new javax.swing.JLabel();
        pnl_genderGr = new javax.swing.JPanel();
        rad_men = new javax.swing.JRadioButton();
        rad_women = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_id4 = new javax.swing.JLabel();
        txt_id4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbl_id5 = new javax.swing.JLabel();
        txt_id5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbl_id6 = new javax.swing.JLabel();
        txt_id2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lbl_id7 = new javax.swing.JLabel();
        txt_id6 = new javax.swing.JTextField();
        pnl_infoFooter = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        pnl_searchCustomer = new javax.swing.JPanel();
        pnl_searchForPhone = new javax.swing.JPanel();
        txt_searchForPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnl_filterCustomer = new javax.swing.JPanel();
        pnl_filterGender = new javax.swing.JPanel();
        lbl_filterGender = new javax.swing.JLabel();
        cbo_filterGender = new javax.swing.JComboBox<>();
        pnl_filterRank = new javax.swing.JPanel();
        lbl_filterRank = new javax.swing.JLabel();
        cbo_filterRank = new javax.swing.JComboBox<>();
        btn_filter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jTable1.setFont(jTable1.getFont().deriveFont((float)14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ và tên", "Ngày sinh", "Số điện thoại", "Giới tính", "Hạng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        pnl_info.setPreferredSize(new java.awt.Dimension(500, 464));
        pnl_info.setLayout(new java.awt.BorderLayout());

        pnl_infoBody.setLayout(new javax.swing.BoxLayout(pnl_infoBody, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        lbl_id.setFont(lbl_id.getFont().deriveFont((float)16));
        lbl_id.setText("Mã:");
        lbl_id.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel1.add(lbl_id);

        txt_id.setEditable(false);
        txt_id.setFont(txt_id.getFont().deriveFont((float)16));
        txt_id.setText("KH0212012332003");
        txt_id.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)));
        txt_id.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id);

        pnl_infoBody.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        lbl_id1.setFont(lbl_id1.getFont().deriveFont((float)16));
        lbl_id1.setText("Họ và tên:");
        lbl_id1.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel2.add(lbl_id1);

        txt_id1.setFont(txt_id1.getFont().deriveFont((float)16));
        txt_id1.setText("Lê Hoàng Khang");
        txt_id1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        txt_id1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(txt_id1);

        pnl_infoBody.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 16));
        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        lbl_id2.setFont(lbl_id2.getFont().deriveFont((float)16));
        lbl_id2.setText("Ngày sinh:");
        lbl_id2.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(lbl_id2);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jDateChooser1.setDateFormatString("MMMM d, yyyy");
        jDateChooser1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(jDateChooser1);

        pnl_infoBody.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel4.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        lbl_id3.setFont(lbl_id3.getFont().deriveFont((float)16));
        lbl_id3.setText("Giới tính:");
        lbl_id3.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel4.add(lbl_id3);

        pnl_genderGr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        pnl_genderGr.setLayout(new javax.swing.BoxLayout(pnl_genderGr, javax.swing.BoxLayout.X_AXIS));

        grp_gender.add(rad_men);
        rad_men.setFont(rad_men.getFont().deriveFont((float)16));
        rad_men.setText("Nam");
        pnl_genderGr.add(rad_men);

        grp_gender.add(rad_women);
        rad_women.setFont(rad_women.getFont().deriveFont((float)16));
        rad_women.setText("Nữ");
        rad_women.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_womenActionPerformed(evt);
            }
        });
        pnl_genderGr.add(rad_women);

        jPanel4.add(pnl_genderGr);

        pnl_infoBody.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel5.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        lbl_id4.setFont(lbl_id4.getFont().deriveFont((float)16));
        lbl_id4.setText("Số điện thoại:");
        lbl_id4.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel5.add(lbl_id4);

        txt_id4.setFont(txt_id4.getFont().deriveFont((float)16));
        txt_id4.setText("0383741660");
        txt_id4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        txt_id4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(txt_id4);

        pnl_infoBody.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        lbl_id5.setFont(lbl_id5.getFont().deriveFont((float)16));
        lbl_id5.setText("Địa chỉ:");
        lbl_id5.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel6.add(lbl_id5);

        txt_id5.setFont(txt_id5.getFont().deriveFont((float)16));
        txt_id5.setText("201/23/13 Nguyễn Thái Sơn, Gò Vấp, Hồ Chí Minh");
        txt_id5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        txt_id5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(txt_id5);

        pnl_infoBody.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel7.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        lbl_id6.setFont(lbl_id6.getFont().deriveFont((float)16));
        lbl_id6.setText("Điểm thành viên:");
        lbl_id6.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel7.add(lbl_id6);

        txt_id2.setFont(txt_id2.getFont().deriveFont((float)16));
        txt_id2.setText("12560");
        txt_id2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        txt_id2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(txt_id2);

        pnl_infoBody.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 15, 16));
        jPanel8.setMaximumSize(new java.awt.Dimension(1000, 70));
        jPanel8.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        lbl_id7.setFont(lbl_id7.getFont().deriveFont((float)14));
        lbl_id7.setText("Hạng thành viên:");
        lbl_id7.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel8.add(lbl_id7);

        txt_id6.setFont(txt_id6.getFont().deriveFont((float)16));
        txt_id6.setText("Kim cương");
        txt_id6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        txt_id6.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel8.add(txt_id6);

        pnl_infoBody.add(jPanel8);

        pnl_info.add(pnl_infoBody, java.awt.BorderLayout.CENTER);

        pnl_infoFooter.setLayout(new javax.swing.BoxLayout(pnl_infoFooter, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getStyle() | java.awt.Font.BOLD, 14));
        jButton2.setText("Thêm");
        jPanel9.add(jButton2);

        jButton3.setFont(jButton3.getFont().deriveFont(jButton3.getFont().getStyle() | java.awt.Font.BOLD, 14));
        jButton3.setText("Reload");
        jPanel9.add(jButton3);

        pnl_infoFooter.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel10.setLayout(new java.awt.GridLayout(1, 1));

        jButton4.setFont(jButton4.getFont().deriveFont(jButton4.getFont().getStyle() | java.awt.Font.BOLD, 14));
        jButton4.setText("Cập nhật thông tin");
        jButton4.putClientProperty(FlatClientProperties.STYLE, "background: $Menu.background;"+"foreground: $Menu.foreground");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4);

        pnl_infoFooter.add(jPanel10);

        pnl_info.add(pnl_infoFooter, java.awt.BorderLayout.SOUTH);

        add(pnl_info, java.awt.BorderLayout.LINE_END);

        pnl_searchCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50));
        pnl_searchCustomer.setLayout(new javax.swing.BoxLayout(pnl_searchCustomer, javax.swing.BoxLayout.LINE_AXIS));

        pnl_searchForPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 50));
        pnl_searchForPhone.setLayout(new javax.swing.BoxLayout(pnl_searchForPhone, javax.swing.BoxLayout.X_AXIS));

        txt_searchForPhone.setText("0383741660");
        txt_searchForPhone.setPreferredSize(new java.awt.Dimension(50, 22));
        txt_searchForPhone.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Số điện thoại người dùng");
        pnl_searchForPhone.add(txt_searchForPhone);

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_searchForPhone.add(jButton1);

        jButton5.setText("Reload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnl_searchForPhone.add(jButton5);

        pnl_searchCustomer.add(pnl_searchForPhone);

        pnl_filterCustomer.setLayout(new javax.swing.BoxLayout(pnl_filterCustomer, javax.swing.BoxLayout.X_AXIS));

        pnl_filterGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pnl_filterGender.setLayout(new javax.swing.BoxLayout(pnl_filterGender, javax.swing.BoxLayout.LINE_AXIS));

        lbl_filterGender.setFont(lbl_filterGender.getFont().deriveFont((float)14));
        lbl_filterGender.setText("Giới tính:");
        pnl_filterGender.add(lbl_filterGender);

        cbo_filterGender.setFont(cbo_filterGender.getFont().deriveFont((float)14));
        cbo_filterGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Nam", "Nữ" }));
        pnl_filterGender.add(cbo_filterGender);

        pnl_filterCustomer.add(pnl_filterGender);

        pnl_filterRank.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        pnl_filterRank.setLayout(new javax.swing.BoxLayout(pnl_filterRank, javax.swing.BoxLayout.LINE_AXIS));

        lbl_filterRank.setFont(lbl_filterRank.getFont().deriveFont((float)14));
        lbl_filterRank.setText("Hạng");
        pnl_filterRank.add(lbl_filterRank);

        cbo_filterRank.setFont(cbo_filterRank.getFont().deriveFont((float)14));
        cbo_filterRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bạc", "Vàng", "Kim Cương" }));
        cbo_filterRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_filterRankActionPerformed(evt);
            }
        });
        pnl_filterRank.add(cbo_filterRank);

        pnl_filterCustomer.add(pnl_filterRank);

        pnl_searchCustomer.add(pnl_filterCustomer);

        btn_filter.setText("Lọc");
        pnl_searchCustomer.add(btn_filter);

        add(pnl_searchCustomer, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbo_filterRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_filterRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_filterRankActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void rad_womenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_womenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_womenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> cbo_filterGender;
    private javax.swing.JComboBox<String> cbo_filterRank;
    private javax.swing.ButtonGroup grp_gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_filterGender;
    private javax.swing.JLabel lbl_filterRank;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_id2;
    private javax.swing.JLabel lbl_id3;
    private javax.swing.JLabel lbl_id4;
    private javax.swing.JLabel lbl_id5;
    private javax.swing.JLabel lbl_id6;
    private javax.swing.JLabel lbl_id7;
    private javax.swing.JPanel pnl_filterCustomer;
    private javax.swing.JPanel pnl_filterGender;
    private javax.swing.JPanel pnl_filterRank;
    private javax.swing.JPanel pnl_genderGr;
    private javax.swing.JPanel pnl_info;
    private javax.swing.JPanel pnl_infoBody;
    private javax.swing.JPanel pnl_infoFooter;
    private javax.swing.JPanel pnl_searchCustomer;
    private javax.swing.JPanel pnl_searchForPhone;
    private javax.swing.JRadioButton rad_men;
    private javax.swing.JRadioButton rad_women;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_id4;
    private javax.swing.JTextField txt_id5;
    private javax.swing.JTextField txt_id6;
    private javax.swing.JTextField txt_searchForPhone;
    // End of variables declaration//GEN-END:variables
}
