/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Như Tâm
 */
public class EmployeeManagement_GUI extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeManagement_GUI
     */
    public EmployeeManagement_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_gender = new javax.swing.ButtonGroup();
        pnl_topEmp = new javax.swing.JPanel();
        pnl_searchEmp = new javax.swing.JPanel();
        txt_searchEmp = new javax.swing.JTextField();
        pnl_btnSearchEmp = new javax.swing.JPanel();
        btn_searchEmp = new javax.swing.JButton();
        pnl_cmb = new javax.swing.JPanel();
        cmb_roleEmp = new javax.swing.JComboBox<>();
        cmb_statusEmp = new javax.swing.JComboBox<>();
        lbl_reloadEmp = new javax.swing.JLabel();
        pnl_centerEmp = new javax.swing.JPanel();
        spl_inforEmp = new javax.swing.JSplitPane();
        scr_tableInforEmp = new javax.swing.JScrollPane();
        tbl_employeeInfor = new javax.swing.JTable();
        pnl_inforDetailEmp = new javax.swing.JPanel();
        pnl_txtInforEmp = new javax.swing.JPanel();
        pnl_empID = new javax.swing.JPanel();
        lbl_empID = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        pnl_nameEmp = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        pnl_addressEmp = new javax.swing.JPanel();
        lbl_addressEmp = new javax.swing.JLabel();
        txt_addressEmp = new javax.swing.JTextField();
        pnl_genderEmp = new javax.swing.JPanel();
        lbl_genderEmp = new javax.swing.JLabel();
        pnl_genderRadioEmp = new javax.swing.JPanel();
        rad_female = new javax.swing.JRadioButton();
        rad_male = new javax.swing.JRadioButton();
        pnl_phoneNumberEmp = new javax.swing.JPanel();
        lbl_phoneNumberEmp = new javax.swing.JLabel();
        txt_phoneNumberEmp = new javax.swing.JTextField();
        pnl_citizenIDEmp = new javax.swing.JPanel();
        lbl_citizenID = new javax.swing.JLabel();
        txt_citizenIDEmp = new javax.swing.JTextField();
        pnl_statusEmp = new javax.swing.JPanel();
        lbl_statusEmp = new javax.swing.JLabel();
        txt_statusEmp = new javax.swing.JTextField();
        pnl_password = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        pnl_btnEmp = new javax.swing.JPanel();
        pnl_buttonEmp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_addEmp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_updateEmp = new javax.swing.JButton();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_topEmp.setMinimumSize(new java.awt.Dimension(20, 20));
        pnl_topEmp.setPreferredSize(new java.awt.Dimension(1368, 70));
        pnl_topEmp.setLayout(new javax.swing.BoxLayout(pnl_topEmp, javax.swing.BoxLayout.X_AXIS));

        pnl_searchEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_searchEmp.setLayout(new javax.swing.BoxLayout(pnl_searchEmp, javax.swing.BoxLayout.X_AXIS));

        txt_searchEmp.setPreferredSize(new java.awt.Dimension(500, 30));
        txt_searchEmp.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Nhập mã nhân viên");
        txt_searchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchEmpActionPerformed(evt);
            }
        });
        pnl_searchEmp.add(txt_searchEmp);

        pnl_btnSearchEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_btnSearchEmp.setLayout(new java.awt.BorderLayout());

        btn_searchEmp.setText("Tìm kiếm");
        btn_searchEmp.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        pnl_btnSearchEmp.add(btn_searchEmp, java.awt.BorderLayout.CENTER);

        pnl_searchEmp.add(pnl_btnSearchEmp);

        pnl_topEmp.add(pnl_searchEmp);

        pnl_cmb.setMaximumSize(new java.awt.Dimension(600, 32767));
        pnl_cmb.setPreferredSize(new java.awt.Dimension(600, 100));
        pnl_cmb.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 17));

        cmb_roleEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ", "NV Bán Hàng", "Cửa Hàng Trưởng", "Kiểm Sát Viên" }));
        cmb_roleEmp.setPreferredSize(new java.awt.Dimension(128, 32));
        pnl_cmb.add(cmb_roleEmp);

        cmb_statusEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Đang làm việc", "Đã nghỉ" }));
        cmb_statusEmp.setPreferredSize(new java.awt.Dimension(128, 32));
        pnl_cmb.add(cmb_statusEmp);

        lbl_reloadEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/employee/reload_employee.png"))); // NOI18N
        pnl_cmb.add(lbl_reloadEmp);

        pnl_topEmp.add(pnl_cmb);

        add(pnl_topEmp, java.awt.BorderLayout.PAGE_START);

        pnl_centerEmp.setLayout(new javax.swing.BoxLayout(pnl_centerEmp, javax.swing.BoxLayout.LINE_AXIS));

        scr_tableInforEmp.setMinimumSize(new java.awt.Dimension(400, 20));
        scr_tableInforEmp.setPreferredSize(new java.awt.Dimension(800, 402));

        tbl_employeeInfor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NV020032023001", "Hồ  Thị Như Tâm", "03-11-2003", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_employeeInfor.setPreferredSize(new java.awt.Dimension(600, 80));
        tbl_employeeInfor.setShowGrid(true);
        scr_tableInforEmp.setViewportView(tbl_employeeInfor);
        if (tbl_employeeInfor.getColumnModel().getColumnCount() > 0) {
            tbl_employeeInfor.getColumnModel().getColumn(1).setResizable(false);
            tbl_employeeInfor.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        spl_inforEmp.setLeftComponent(scr_tableInforEmp);

        pnl_inforDetailEmp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_inforDetailEmp.setPreferredSize(new java.awt.Dimension(200, 100));
        pnl_inforDetailEmp.setLayout(new java.awt.BorderLayout());

        pnl_txtInforEmp.setLayout(new javax.swing.BoxLayout(pnl_txtInforEmp, javax.swing.BoxLayout.Y_AXIS));

        pnl_empID.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_empID.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_empID.setPreferredSize(new java.awt.Dimension(210, 40));
        pnl_empID.setLayout(new javax.swing.BoxLayout(pnl_empID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_empID.setText("Mã NV:");
        lbl_empID.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_empID.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_empID.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_empID.add(lbl_empID);

        txt_empID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_empID.setText("NV020032023001");
        txt_empID.setBorder(null);
        txt_empID.setEnabled(false);
        txt_empID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_empID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_empID.setPreferredSize(new java.awt.Dimension(150, 30));
        pnl_empID.add(txt_empID);

        pnl_txtInforEmp.add(pnl_empID);

        pnl_nameEmp.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_nameEmp.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_nameEmp.setLayout(new javax.swing.BoxLayout(pnl_nameEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_name.setText("Họ tên:");
        lbl_name.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_nameEmp.add(lbl_name);

        txt_name.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_name.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_name.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_nameEmp.add(txt_name);

        pnl_txtInforEmp.add(pnl_nameEmp);

        pnl_addressEmp.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_addressEmp.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_addressEmp.setLayout(new javax.swing.BoxLayout(pnl_addressEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_addressEmp.setText("Địa chỉ:");
        lbl_addressEmp.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_addressEmp.add(lbl_addressEmp);

        txt_addressEmp.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_addressEmp.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_addressEmp.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_addressEmp.add(txt_addressEmp);

        pnl_txtInforEmp.add(pnl_addressEmp);

        pnl_genderEmp.setMaximumSize(new java.awt.Dimension(32815, 40));
        pnl_genderEmp.setPreferredSize(new java.awt.Dimension(183, 40));
        pnl_genderEmp.setLayout(new javax.swing.BoxLayout(pnl_genderEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_genderEmp.setText("Giới tính:");
        lbl_genderEmp.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_genderEmp.add(lbl_genderEmp);

        pnl_genderRadioEmp.setMaximumSize(new java.awt.Dimension(32767, 30));
        pnl_genderRadioEmp.setMinimumSize(new java.awt.Dimension(103, 30));
        pnl_genderRadioEmp.setPreferredSize(new java.awt.Dimension(103, 30));
        pnl_genderRadioEmp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        group_gender.add(rad_female);
        rad_female.setSelected(true);
        rad_female.setText("Nữ");
        rad_female.setEnabled(false);
        rad_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_femaleActionPerformed(evt);
            }
        });
        pnl_genderRadioEmp.add(rad_female);

        group_gender.add(rad_male);
        rad_male.setText("Nam");
        rad_male.setEnabled(false);
        pnl_genderRadioEmp.add(rad_male);

        pnl_genderEmp.add(pnl_genderRadioEmp);

        pnl_txtInforEmp.add(pnl_genderEmp);

        pnl_phoneNumberEmp.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_phoneNumberEmp.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_phoneNumberEmp.setLayout(new javax.swing.BoxLayout(pnl_phoneNumberEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_phoneNumberEmp.setText("SDT:");
        lbl_phoneNumberEmp.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_phoneNumberEmp.add(lbl_phoneNumberEmp);

        txt_phoneNumberEmp.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_phoneNumberEmp.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_phoneNumberEmp.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_phoneNumberEmp.add(txt_phoneNumberEmp);

        pnl_txtInforEmp.add(pnl_phoneNumberEmp);

        pnl_citizenIDEmp.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_citizenIDEmp.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_citizenIDEmp.setLayout(new javax.swing.BoxLayout(pnl_citizenIDEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_citizenID.setText("CCCD:");
        lbl_citizenID.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_citizenIDEmp.add(lbl_citizenID);

        txt_citizenIDEmp.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_citizenIDEmp.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_citizenIDEmp.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_citizenIDEmp.add(txt_citizenIDEmp);

        pnl_txtInforEmp.add(pnl_citizenIDEmp);

        pnl_statusEmp.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_statusEmp.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_statusEmp.setLayout(new javax.swing.BoxLayout(pnl_statusEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_statusEmp.setText("Trạng thái:");
        lbl_statusEmp.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_statusEmp.add(lbl_statusEmp);

        txt_statusEmp.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_statusEmp.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_statusEmp.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_statusEmp.add(txt_statusEmp);

        pnl_txtInforEmp.add(pnl_statusEmp);

        pnl_password.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_password.setPreferredSize(new java.awt.Dimension(230, 40));
        pnl_password.setLayout(new javax.swing.BoxLayout(pnl_password, javax.swing.BoxLayout.LINE_AXIS));

        lbl_password.setText("Mật khẩu:");
        lbl_password.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_password.add(lbl_password);

        txt_password.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_password.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_password.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_password.add(txt_password);

        pnl_txtInforEmp.add(pnl_password);

        pnl_inforDetailEmp.add(pnl_txtInforEmp, java.awt.BorderLayout.CENTER);

        pnl_btnEmp.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        pnl_btnEmp.setMinimumSize(new java.awt.Dimension(176, 100));
        pnl_btnEmp.setLayout(new javax.swing.BoxLayout(pnl_btnEmp, javax.swing.BoxLayout.X_AXIS));

        pnl_buttonEmp.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        pnl_buttonEmp.setMinimumSize(new java.awt.Dimension(176, 50));
        pnl_buttonEmp.setPreferredSize(new java.awt.Dimension(176, 50));
        pnl_buttonEmp.setLayout(new javax.swing.BoxLayout(pnl_buttonEmp, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_addEmp.setText("Thêm NV");
        btn_addEmp.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        jPanel1.add(btn_addEmp, java.awt.BorderLayout.CENTER);

        pnl_buttonEmp.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_updateEmp.setText("Cập nhật NV");
        btn_updateEmp.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        jPanel2.add(btn_updateEmp, java.awt.BorderLayout.CENTER);

        pnl_buttonEmp.add(jPanel2);

        pnl_btnEmp.add(pnl_buttonEmp);

        pnl_inforDetailEmp.add(pnl_btnEmp, java.awt.BorderLayout.SOUTH);

        spl_inforEmp.setRightComponent(pnl_inforDetailEmp);

        pnl_centerEmp.add(spl_inforEmp);

        add(pnl_centerEmp, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchEmpActionPerformed

    private void rad_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_femaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEmp;
    private javax.swing.JButton btn_searchEmp;
    private javax.swing.JButton btn_updateEmp;
    private javax.swing.JComboBox<String> cmb_roleEmp;
    private javax.swing.JComboBox<String> cmb_statusEmp;
    private javax.swing.ButtonGroup group_gender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_addressEmp;
    private javax.swing.JLabel lbl_citizenID;
    private javax.swing.JLabel lbl_empID;
    private javax.swing.JLabel lbl_genderEmp;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phoneNumberEmp;
    private javax.swing.JLabel lbl_reloadEmp;
    private javax.swing.JLabel lbl_statusEmp;
    private javax.swing.JPanel pnl_addressEmp;
    private javax.swing.JPanel pnl_btnEmp;
    private javax.swing.JPanel pnl_btnSearchEmp;
    private javax.swing.JPanel pnl_buttonEmp;
    private javax.swing.JPanel pnl_centerEmp;
    private javax.swing.JPanel pnl_citizenIDEmp;
    private javax.swing.JPanel pnl_cmb;
    private javax.swing.JPanel pnl_empID;
    private javax.swing.JPanel pnl_genderEmp;
    private javax.swing.JPanel pnl_genderRadioEmp;
    private javax.swing.JPanel pnl_inforDetailEmp;
    private javax.swing.JPanel pnl_nameEmp;
    private javax.swing.JPanel pnl_password;
    private javax.swing.JPanel pnl_phoneNumberEmp;
    private javax.swing.JPanel pnl_searchEmp;
    private javax.swing.JPanel pnl_statusEmp;
    private javax.swing.JPanel pnl_topEmp;
    private javax.swing.JPanel pnl_txtInforEmp;
    private javax.swing.JRadioButton rad_female;
    private javax.swing.JRadioButton rad_male;
    private javax.swing.JScrollPane scr_tableInforEmp;
    private javax.swing.JSplitPane spl_inforEmp;
    private javax.swing.JTable tbl_employeeInfor;
    private javax.swing.JTextField txt_addressEmp;
    private javax.swing.JTextField txt_citizenIDEmp;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phoneNumberEmp;
    private javax.swing.JTextField txt_searchEmp;
    private javax.swing.JTextField txt_statusEmp;
    // End of variables declaration//GEN-END:variables
}
