/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Như Tâm
 */
public class EmployeeManagement_GUI extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeManagement_GUI
     */
    public EmployeeManagement_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_gender = new javax.swing.ButtonGroup();
        pnl_top = new javax.swing.JPanel();
        txt_employeeSearch = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        cmb_role = new javax.swing.JComboBox<>();
        lbl_reloadEmp = new javax.swing.JLabel();
        pnl_centerEmp = new javax.swing.JPanel();
        spl_inforEmp = new javax.swing.JSplitPane();
        scr_tableInfor = new javax.swing.JScrollPane();
        tbl_employeeInfor = new javax.swing.JTable();
        pnl_inforDetailEmp = new javax.swing.JPanel();
        pnl_empID = new javax.swing.JPanel();
        lbl_empID = new javax.swing.JLabel();
        txt_empID = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_nameEmp = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_addressEmp = new javax.swing.JPanel();
        lbl_addressEmp = new javax.swing.JLabel();
        txt_addressEmp = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_gender = new javax.swing.JPanel();
        lbl_gender = new javax.swing.JLabel();
        pnl_genderRadio = new javax.swing.JPanel();
        rad_female = new javax.swing.JRadioButton();
        rad_male = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_phoneNumberEmp = new javax.swing.JPanel();
        lbl_phoneNumber = new javax.swing.JLabel();
        txt_phoneNumber = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_citizenIDEmp = new javax.swing.JPanel();
        lbl_citizenID = new javax.swing.JLabel();
        txt_citizenIDEmp = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_statusEmp = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        txt_statusEmp = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        pnl_password = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        pnl_bottom = new javax.swing.JPanel();
        btn_updateEmp = new javax.swing.JButton();
        btn_addEmp = new javax.swing.JButton();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_top.setMinimumSize(new java.awt.Dimension(20, 20));
        pnl_top.setPreferredSize(new java.awt.Dimension(1368, 70));
        pnl_top.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        txt_employeeSearch.setPreferredSize(new java.awt.Dimension(500, 30));
        txt_employeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeSearchActionPerformed(evt);
            }
        });
        pnl_top.add(txt_employeeSearch);

        btn_search.setText("Tìm kiếm");
        pnl_top.add(btn_search);

        cmb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ", "NV Bán Hàng", "Cửa Hàng Trưởng", "Kiểm Sát Viên" }));
        pnl_top.add(cmb_role);

        lbl_reloadEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/employee/reload_employee.png"))); // NOI18N
        pnl_top.add(lbl_reloadEmp);

        add(pnl_top, java.awt.BorderLayout.PAGE_START);

        pnl_centerEmp.setLayout(new javax.swing.BoxLayout(pnl_centerEmp, javax.swing.BoxLayout.LINE_AXIS));

        scr_tableInfor.setMinimumSize(new java.awt.Dimension(800, 20));
        scr_tableInfor.setPreferredSize(new java.awt.Dimension(800, 402));

        tbl_employeeInfor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_employeeInfor.setPreferredSize(new java.awt.Dimension(600, 80));
        tbl_employeeInfor.setShowGrid(true);
        scr_tableInfor.setViewportView(tbl_employeeInfor);
        if (tbl_employeeInfor.getColumnModel().getColumnCount() > 0) {
            tbl_employeeInfor.getColumnModel().getColumn(1).setResizable(false);
            tbl_employeeInfor.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        spl_inforEmp.setLeftComponent(scr_tableInfor);

        pnl_inforDetailEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        pnl_inforDetailEmp.setPreferredSize(new java.awt.Dimension(200, 100));
        pnl_inforDetailEmp.setLayout(new java.awt.GridLayout(15, 1, 10, 0));

        pnl_empID.setMinimumSize(new java.awt.Dimension(118, 6));
        pnl_empID.setPreferredSize(new java.awt.Dimension(210, 30));
        pnl_empID.setLayout(new javax.swing.BoxLayout(pnl_empID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_empID.setText("Mã nhân viên:");
        lbl_empID.setMaximumSize(new java.awt.Dimension(45, 16));
        lbl_empID.setMinimumSize(new java.awt.Dimension(45, 16));
        lbl_empID.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_empID.add(lbl_empID);

        txt_empID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_empID.setBorder(null);
        txt_empID.setEnabled(false);
        txt_empID.setPreferredSize(new java.awt.Dimension(200, 15));
        pnl_empID.add(txt_empID);

        pnl_inforDetailEmp.add(pnl_empID);
        pnl_inforDetailEmp.add(filler1);

        pnl_nameEmp.setLayout(new javax.swing.BoxLayout(pnl_nameEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_name.setText("Họ tên:");
        lbl_name.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_nameEmp.add(lbl_name);

        txt_name.setPreferredSize(txt_empID.getPreferredSize());
        pnl_nameEmp.add(txt_name);

        pnl_inforDetailEmp.add(pnl_nameEmp);
        pnl_inforDetailEmp.add(filler2);

        pnl_addressEmp.setLayout(new javax.swing.BoxLayout(pnl_addressEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_addressEmp.setText("Địa chỉ:");
        lbl_addressEmp.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_addressEmp.add(lbl_addressEmp);

        txt_addressEmp.setPreferredSize(txt_empID.getPreferredSize());
        pnl_addressEmp.add(txt_addressEmp);

        pnl_inforDetailEmp.add(pnl_addressEmp);
        pnl_inforDetailEmp.add(filler3);

        pnl_gender.setLayout(new javax.swing.BoxLayout(pnl_gender, javax.swing.BoxLayout.LINE_AXIS));

        lbl_gender.setText("Giới tính:");
        lbl_gender.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_gender.add(lbl_gender);

        pnl_genderRadio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        group_gender.add(rad_female);
        rad_female.setSelected(true);
        rad_female.setText("Nữ");
        rad_female.setEnabled(false);
        rad_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_femaleActionPerformed(evt);
            }
        });
        pnl_genderRadio.add(rad_female);

        group_gender.add(rad_male);
        rad_male.setText("Nam");
        rad_male.setEnabled(false);
        pnl_genderRadio.add(rad_male);

        pnl_gender.add(pnl_genderRadio);

        pnl_inforDetailEmp.add(pnl_gender);
        pnl_inforDetailEmp.add(filler4);

        pnl_phoneNumberEmp.setLayout(new javax.swing.BoxLayout(pnl_phoneNumberEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_phoneNumber.setText("SDT:");
        lbl_phoneNumber.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_phoneNumberEmp.add(lbl_phoneNumber);

        txt_phoneNumber.setPreferredSize(txt_empID.getPreferredSize());
        pnl_phoneNumberEmp.add(txt_phoneNumber);

        pnl_inforDetailEmp.add(pnl_phoneNumberEmp);
        pnl_inforDetailEmp.add(filler5);

        pnl_citizenIDEmp.setLayout(new javax.swing.BoxLayout(pnl_citizenIDEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_citizenID.setText("CCCD:");
        lbl_citizenID.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_citizenIDEmp.add(lbl_citizenID);

        txt_citizenIDEmp.setPreferredSize(txt_empID.getPreferredSize());
        pnl_citizenIDEmp.add(txt_citizenIDEmp);

        pnl_inforDetailEmp.add(pnl_citizenIDEmp);
        pnl_inforDetailEmp.add(filler6);

        pnl_statusEmp.setLayout(new javax.swing.BoxLayout(pnl_statusEmp, javax.swing.BoxLayout.LINE_AXIS));

        lbl_status.setText("Trạng thái:");
        lbl_status.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_statusEmp.add(lbl_status);

        txt_statusEmp.setPreferredSize(txt_empID.getPreferredSize());
        pnl_statusEmp.add(txt_statusEmp);

        pnl_inforDetailEmp.add(pnl_statusEmp);
        pnl_inforDetailEmp.add(filler7);

        pnl_password.setLayout(new javax.swing.BoxLayout(pnl_password, javax.swing.BoxLayout.LINE_AXIS));

        lbl_password.setText("Mật khẩu:");
        lbl_password.setPreferredSize(lbl_empID.getPreferredSize());
        pnl_password.add(lbl_password);

        txt_password.setPreferredSize(txt_empID.getPreferredSize());
        pnl_password.add(txt_password);

        pnl_inforDetailEmp.add(pnl_password);

        spl_inforEmp.setRightComponent(pnl_inforDetailEmp);

        pnl_centerEmp.add(spl_inforEmp);

        add(pnl_centerEmp, java.awt.BorderLayout.CENTER);

        pnl_bottom.setPreferredSize(new java.awt.Dimension(1368, 50));
        pnl_bottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btn_updateEmp.setText("Cập nhật NV");
        pnl_bottom.add(btn_updateEmp);

        btn_addEmp.setText("Thêm NV");
        pnl_bottom.add(btn_addEmp);

        add(pnl_bottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeSearchActionPerformed

    private void rad_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_femaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEmp;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_updateEmp;
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.ButtonGroup group_gender;
    private javax.swing.JLabel lbl_addressEmp;
    private javax.swing.JLabel lbl_citizenID;
    private javax.swing.JLabel lbl_empID;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_reloadEmp;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel pnl_addressEmp;
    private javax.swing.JPanel pnl_bottom;
    private javax.swing.JPanel pnl_centerEmp;
    private javax.swing.JPanel pnl_citizenIDEmp;
    private javax.swing.JPanel pnl_empID;
    private javax.swing.JPanel pnl_gender;
    private javax.swing.JPanel pnl_genderRadio;
    private javax.swing.JPanel pnl_inforDetailEmp;
    private javax.swing.JPanel pnl_nameEmp;
    private javax.swing.JPanel pnl_password;
    private javax.swing.JPanel pnl_phoneNumberEmp;
    private javax.swing.JPanel pnl_statusEmp;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JRadioButton rad_female;
    private javax.swing.JRadioButton rad_male;
    private javax.swing.JScrollPane scr_tableInfor;
    private javax.swing.JSplitPane spl_inforEmp;
    private javax.swing.JTable tbl_employeeInfor;
    private javax.swing.JTextField txt_addressEmp;
    private javax.swing.JTextField txt_citizenIDEmp;
    private javax.swing.JTextField txt_empID;
    private javax.swing.JTextField txt_employeeSearch;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_statusEmp;
    // End of variables declaration//GEN-END:variables
}
