/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.Login_BUS;
import com.formdev.flatlaf.FlatClientProperties;
import entity.Account;
import entity.Employee;
import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import main.Application;
import raven.toast.Notifications;
import utilities.PasswordHash;

/**
 *
 * @author Hoàng Khang
 */
public class Login_GUI extends javax.swing.JPanel {

    private final Login_BUS log_BUS = new Login_BUS();

    /**
     * Creates new form Password_Change
     */
    public Login_GUI() {
        initComponents();
        setPositionForm();

    }

    public void setPositionForm() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int centerX = (screenWidth - 400) / 2;
        int centerY = (screenHeight - 350) / 2 - 50;

        pnl_loginForm.setBounds(centerX, centerY, 400, 350);

        centerX = (screenWidth - 400) / 2;
        centerY = (screenHeight - 520) / 2 - 50;

        pnl_changePasswordForm.setBounds(centerX, centerY, 400, 520);

        pnl_changePasswordForm.setVisible(false);
    }

    public boolean checkValueFormChangePassword(String id, String pass, String passNew, String passConfirm) throws Exception {
        if (id.equals("")) {
            throw new Exception("Mã đăng nhập không được bỏ trống!");
        }
        if (pass.equals("")) {
            throw new Exception("Mật khẩu không được bỏ trống!");
        }
        if (passNew.equals("")) {
            throw new Exception("Mật khẩu mới không được bỏ trống!");
        }
        if (passConfirm.equals("")) {
            throw new Exception("Bạn chưa xác nhận mật khẩu mới");
        }
        if (!passNew.equals(passConfirm)) {
            throw new Exception("Mật khẩu xác nhận không trùng khớp!");
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fra_ChangePassword = new javax.swing.JFrame();
        pnl_login = new javax.swing.JPanel();
        pnl_loginForm = new javax.swing.JPanel();
        lbl_titleLogin = new javax.swing.JLabel();
        lbl_accountLogin = new javax.swing.JLabel();
        lbl_passwordLogin = new javax.swing.JLabel();
        pwr_passwordLogin = new javax.swing.JPasswordField();
        txt_accountLogin = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        lbl_navChangePassword = new javax.swing.JLabel();
        pnl_changePasswordForm = new javax.swing.JPanel();
        lbl_titleChangePassword = new javax.swing.JLabel();
        lbl_account = new javax.swing.JLabel();
        lbl_passwordNew = new javax.swing.JLabel();
        pwr_passwordNew = new javax.swing.JPasswordField();
        txt_account = new javax.swing.JTextField();
        btn_changePassword = new javax.swing.JButton();
        lbl_passwordConfirm = new javax.swing.JLabel();
        pwr_passwordConfirm = new javax.swing.JPasswordField();
        lbl_navLogin = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        pwr_password = new javax.swing.JPasswordField();
        lbl_bachground = new javax.swing.JLabel();

        fra_ChangePassword.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(320, 32767));
        setPreferredSize(new java.awt.Dimension(320, 300));
        setLayout(new java.awt.CardLayout());

        pnl_login.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                pnl_loginAncestorResized(evt);
            }
        });
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_loginForm.setBackground(new java.awt.Color(255, 255, 255));
        pnl_loginForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 10, 30));
        pnl_loginForm.setForeground(new java.awt.Color(255, 255, 255));
        pnl_loginForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_loginForm.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnl_loginForm.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        pnl_loginForm.setMinimumSize(new java.awt.Dimension(529, 70));
        pnl_loginForm.setPreferredSize(new java.awt.Dimension(220, 70));
        pnl_loginForm.setRequestFocusEnabled(false);
        pnl_loginForm.setVerifyInputWhenFocusTarget(false);
        java.awt.GridBagLayout pnl_center1Layout = new java.awt.GridBagLayout();
        pnl_center1Layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        pnl_center1Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        pnl_loginForm.setLayout(pnl_center1Layout);

        lbl_titleLogin.setFont(lbl_titleLogin.getFont().deriveFont(lbl_titleLogin.getFont().getStyle() | java.awt.Font.BOLD, 24));
        lbl_titleLogin.setForeground(new java.awt.Color(71, 118, 185));
        lbl_titleLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titleLogin.setText("Đăng nhập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 18, 0);
        pnl_loginForm.add(lbl_titleLogin, gridBagConstraints);

        lbl_accountLogin.setFont(lbl_accountLogin.getFont().deriveFont((float)18));
        lbl_accountLogin.setText("Tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 19, 0, 0);
        pnl_loginForm.add(lbl_accountLogin, gridBagConstraints);

        lbl_passwordLogin.setFont(lbl_passwordLogin.getFont().deriveFont((float)18));
        lbl_passwordLogin.setText("Mật khẩu");
        lbl_passwordLogin.setMaximumSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_loginForm.add(lbl_passwordLogin, gridBagConstraints);

        pwr_passwordLogin.setText("Lehoangkhang");
        pwr_passwordLogin.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        pwr_passwordLogin.putClientProperty(FlatClientProperties.STYLE, ""
            + "showRevealButton:true;"
            + "showCapsLock:true");
        pwr_passwordLogin.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu");
        pwr_passwordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwr_passwordLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 23);
        pnl_loginForm.add(pwr_passwordLogin, gridBagConstraints);

        txt_accountLogin.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã nhân viên của bạn");
        txt_accountLogin.setText("NV120032023002");
        txt_accountLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_accountLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_loginForm.add(txt_accountLogin, gridBagConstraints);

        btn_login.setText("Đăng nhập");
        btn_login.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_login.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_login.setMinimumSize(new java.awt.Dimension(88, 30));
        btn_login.setPreferredSize(new java.awt.Dimension(88, 30));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 10, 0);
        pnl_loginForm.add(btn_login, gridBagConstraints);

        lbl_navChangePassword.setForeground(new java.awt.Color(71, 118, 185));
        lbl_navChangePassword.setText("Đổi mật khẩu?");
        lbl_navChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_navChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_navChangePasswordMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        pnl_loginForm.add(lbl_navChangePassword, gridBagConstraints);

        pnl_login.add(pnl_loginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 400, 350));
        pnl_loginForm.getAccessibleContext().setAccessibleDescription("");
        int centerX = (pnl_login.getWidth() - pnl_loginForm.getWidth()) / 2;
        int centerY = (pnl_login.getHeight() - pnl_loginForm.getHeight()) / 2;
        pnl_login.setBounds(centerX, centerY, pnl_loginForm.getWidth(), pnl_loginForm.getHeight());

        pnl_changePasswordForm.setBackground(new java.awt.Color(255, 255, 255));
        pnl_changePasswordForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 10, 30));
        pnl_changePasswordForm.setForeground(new java.awt.Color(255, 255, 255));
        pnl_changePasswordForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_changePasswordForm.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnl_changePasswordForm.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        pnl_changePasswordForm.setMinimumSize(new java.awt.Dimension(529, 70));
        pnl_changePasswordForm.setPreferredSize(new java.awt.Dimension(220, 70));
        pnl_changePasswordForm.setRequestFocusEnabled(false);
        pnl_changePasswordForm.setVerifyInputWhenFocusTarget(false);
        java.awt.GridBagLayout pnl_changePasswordFormLayout = new java.awt.GridBagLayout();
        pnl_changePasswordFormLayout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        pnl_changePasswordFormLayout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        pnl_changePasswordForm.setLayout(pnl_changePasswordFormLayout);

        lbl_titleChangePassword.setFont(lbl_titleChangePassword.getFont().deriveFont(lbl_titleChangePassword.getFont().getStyle() | java.awt.Font.BOLD, 24));
        lbl_titleChangePassword.setForeground(new java.awt.Color(71, 118, 185));
        lbl_titleChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titleChangePassword.setText("Đổi mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 18, 0);
        pnl_changePasswordForm.add(lbl_titleChangePassword, gridBagConstraints);

        lbl_account.setFont(lbl_account.getFont().deriveFont((float)18));
        lbl_account.setText("Tài khoản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 19, 0, 0);
        pnl_changePasswordForm.add(lbl_account, gridBagConstraints);

        lbl_passwordNew.setFont(lbl_passwordNew.getFont().deriveFont((float)18));
        lbl_passwordNew.setText("Mật khẩu mới:");
        lbl_passwordNew.setMaximumSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(lbl_passwordNew, gridBagConstraints);

        pwr_passwordNew.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        pwr_passwordNew.putClientProperty(FlatClientProperties.STYLE, ""
            + "showRevealButton:true;"
            + "showCapsLock:true");
        pwr_passwordNew.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu mới");
        pwr_passwordNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwr_passwordNewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(pwr_passwordNew, gridBagConstraints);

        txt_account.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã nhân viên của bạn");
        txt_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_accountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(txt_account, gridBagConstraints);

        btn_changePassword.setText("Đổi mật khẩu");
        btn_changePassword.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_changePassword.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_changePassword.setMinimumSize(new java.awt.Dimension(88, 30));
        btn_changePassword.setPreferredSize(new java.awt.Dimension(88, 30));
        btn_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 30, 40);
        pnl_changePasswordForm.add(btn_changePassword, gridBagConstraints);

        lbl_passwordConfirm.setFont(lbl_passwordConfirm.getFont().deriveFont((float)18));
        lbl_passwordConfirm.setText("Xác nhận mật khẩu mới:");
        lbl_passwordConfirm.setMaximumSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(lbl_passwordConfirm, gridBagConstraints);

        pwr_passwordConfirm.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        pwr_passwordConfirm.putClientProperty(FlatClientProperties.STYLE, ""
            + "showRevealButton:true;"
            + "showCapsLock:true");
        pwr_passwordConfirm.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Xác nhận mật khẩu");
        pwr_passwordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwr_passwordConfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(pwr_passwordConfirm, gridBagConstraints);

        lbl_navLogin.setForeground(new java.awt.Color(71, 118, 185));
        lbl_navLogin.setText("Đăng nhập");
        lbl_navLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_navLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_navLoginMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnl_changePasswordForm.add(lbl_navLogin, gridBagConstraints);

        lbl_password.setFont(lbl_password.getFont().deriveFont((float)18));
        lbl_password.setText("Mật khẩu:");
        lbl_password.setMaximumSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(lbl_password, gridBagConstraints);

        pwr_password.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        pwr_password.putClientProperty(FlatClientProperties.STYLE, ""
            + "showRevealButton:true;"
            + "showCapsLock:true");
        pwr_password.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu");
        pwr_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwr_passwordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        pnl_changePasswordForm.add(pwr_password, gridBagConstraints);

        pnl_login.add(pnl_changePasswordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 520));

        lbl_bachground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/login/background.png"))); // NOI18N
        lbl_bachground.setPreferredSize(new java.awt.Dimension(3000,1789));
        pnl_login.add(lbl_bachground, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -40, 3090, 1880));

        add(pnl_login, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_navChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_navChangePasswordMouseClicked
        // TODO add your handling code here:
        pnl_changePasswordForm.setVisible(true);
        pnl_loginForm.setVisible(false);
    }//GEN-LAST:event_lbl_navChangePasswordMouseClicked

    private void lbl_navLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_navLoginMouseClicked
        // TODO add your handling code here:
        pnl_changePasswordForm.setVisible(false);
        pnl_loginForm.setVisible(true);
    }//GEN-LAST:event_lbl_navLoginMouseClicked

    private void txt_accountLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_accountLoginActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_accountLoginActionPerformed

    private void pwr_passwordLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwr_passwordLoginActionPerformed
        // TODO add your handling code here:
        resizeCenterPanel();

    }// GEN-LAST:event_pwr_passwordLoginActionPerformed

    private void pnl_loginAncestorResized(java.awt.event.HierarchyEvent evt) {// GEN-FIRST:event_pnl_loginAncestorResized
        // TODO add your handling code here:
        resizeCenterPanel();
    }// GEN-LAST:event_pnl_loginAncestorResized

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_loginActionPerformed
        String id = txt_accountLogin.getText();
        String password = String.copyValueOf(pwr_passwordLogin.getPassword());
        try {
            Employee emp = log_BUS.login(id, password);
            if (emp != null) {
                Application.login(emp);
            }
        } catch (Exception ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, ex.getMessage());
        }

    }// GEN-LAST:event_btn_loginActionPerformed

    private void pwr_passwordNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwr_passwordNewActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pwr_passwordNewActionPerformed

    private void txt_accountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_accountActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_accountActionPerformed

    private void btn_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_changePasswordActionPerformed
        // TODO add your handling code here:
        String id = txt_account.getText();
        String pass = String.valueOf(pwr_password.getPassword());
        String passNew = String.valueOf(pwr_passwordNew.getPassword());
        String passConfirm = String.valueOf(pwr_passwordConfirm.getPassword());

        try {
            if (checkValueFormChangePassword(id, pass, passNew, passConfirm)) {
                Account acc = new Account(passNew, new Employee(id));
                if (log_BUS.changePassword(acc, passNew)) {
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, "Đổi mật khẩu thành công!");
                }
            }
        } catch (Exception ex) {
            Notifications.getInstance().show(Notifications.Type.ERROR, ex.getMessage());
        }
    }// GEN-LAST:event_btn_changePasswordActionPerformed

    private void pwr_passwordConfirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwr_passwordConfirmActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pwr_passwordConfirmActionPerformed

    private void pwr_passwordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwr_passwordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pwr_passwordActionPerformed

    private void resizeCenterPanel() {
        if (pnl_login != null && pnl_loginForm != null) {
            int centerX = (pnl_login.getWidth() - pnl_loginForm.getWidth()) / 2;
            int centerY = (pnl_login.getHeight() - pnl_loginForm.getHeight()) / 2;

            pnl_loginForm.setBounds(centerX, centerY, pnl_loginForm.getWidth(), pnl_loginForm.getHeight());
        }

        if (pnl_login != null && pnl_changePasswordForm != null) {
            int centerX = (pnl_login.getWidth() - pnl_changePasswordForm.getWidth()) / 2;
            int centerY = (pnl_login.getHeight() - pnl_changePasswordForm.getHeight()) / 2;

            pnl_changePasswordForm.setBounds(centerX, centerY, pnl_changePasswordForm.getWidth(), pnl_changePasswordForm.getHeight());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changePassword;
    private javax.swing.JButton btn_login;
    private javax.swing.JFrame fra_ChangePassword;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_accountLogin;
    private javax.swing.JLabel lbl_bachground;
    private javax.swing.JLabel lbl_navChangePassword;
    private javax.swing.JLabel lbl_navLogin;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_passwordConfirm;
    private javax.swing.JLabel lbl_passwordLogin;
    private javax.swing.JLabel lbl_passwordNew;
    private javax.swing.JLabel lbl_titleChangePassword;
    private javax.swing.JLabel lbl_titleLogin;
    private javax.swing.JPanel pnl_changePasswordForm;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_loginForm;
    private javax.swing.JPasswordField pwr_password;
    private javax.swing.JPasswordField pwr_passwordConfirm;
    private javax.swing.JPasswordField pwr_passwordLogin;
    private javax.swing.JPasswordField pwr_passwordNew;
    private javax.swing.JTextField txt_account;
    private javax.swing.JTextField txt_accountLogin;
    // End of variables declaration//GEN-END:variables
}
