/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.ShiftsManagemant_BUS;
import entity.Customer;
import entity.Shift;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoàng Khang
 */
public class ManagemantShifts_GUI extends javax.swing.JPanel {

    private DefaultTableModel tblModel_shift;
    private ShiftsManagemant_BUS shift_bus = new ShiftsManagemant_BUS();

    /**
     * Creates new form ManagemantShifts_GUI
     */
    public ManagemantShifts_GUI() {
        initTableModel();
        initComponents();
        renderShiftsTable(shift_bus.getAll());
    }

    public void initTableModel() {
        // Products
        tblModel_shift = new DefaultTableModel(new String[]{"Mã", "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Thời gian đăng nhập", "Thời gian đăng xuất"
        }, 0);
    }

    public void renderShiftsTable(ArrayList<Shift> list) {
        tblModel_shift.setRowCount(0);
        for (Shift shift : list) {
            Object[] row = new Object[]{shift.getShiftID(), shift.getAccount().getEmployee().getEmployeeID(), shift.getAccount().getEmployee().getName(), shift.getAccount().getEmployee().getRole(), shift.getStartedAt(), shift.getEndedAt()};
            tblModel_shift.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr_shifts = new javax.swing.JScrollPane();
        tbl_shifts = new javax.swing.JTable();
        pnl_header = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        tbl_shifts.setModel(tblModel_shift);
        scr_shifts.setViewportView(tbl_shifts);

        add(scr_shifts, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(pnl_header, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_header;
    private javax.swing.JScrollPane scr_shifts;
    private javax.swing.JTable tbl_shifts;
    // End of variables declaration//GEN-END:variables
}
