/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author thanhcanhit
 */
public class ProductManagement_GUI extends javax.swing.JPanel {
    /**
     * Creates new form Sales_GUI
     */
    public ProductManagement_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane_main = new javax.swing.JSplitPane();
        pnl_left = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        pnl_cart = new javax.swing.JPanel();
        scr_cart = new javax.swing.JScrollPane();
        tbl_cart = new javax.swing.JTable();
        pnl_cartFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_right = new javax.swing.JPanel();
        pnl_productInfo = new javax.swing.JPanel();
        pnl_productTop = new javax.swing.JPanel();
        pnl_productTopLeft = new javax.swing.JPanel();
        lbl_productImg = new javax.swing.JLabel();
        pnl_productTopRight = new javax.swing.JPanel();
        pnl_orderId = new javax.swing.JPanel();
        pnl_container = new javax.swing.JPanel();
        lbl_productId = new javax.swing.JLabel();
        txt_productId = new javax.swing.JTextField();
        pnl_container1 = new javax.swing.JPanel();
        lbl_productName = new javax.swing.JLabel();
        scr_productName = new javax.swing.JScrollPane();
        txa_productName = new javax.swing.JTextArea();
        pnl_productCenter = new javax.swing.JPanel();
        pnl_container3 = new javax.swing.JPanel();
        lbl_productCostPrice = new javax.swing.JLabel();
        txt_productCostPrice = new javax.swing.JTextField();
        pnl_container4 = new javax.swing.JPanel();
        lbl_productPrice = new javax.swing.JLabel();
        txt_productPrice = new javax.swing.JTextField();
        pnl_container5 = new javax.swing.JPanel();
        lbl_productInventory = new javax.swing.JLabel();
        txt_productInventory = new javax.swing.JTextField();
        pnl_container6 = new javax.swing.JPanel();
        lbl_productVAT = new javax.swing.JLabel();
        txt_productVAT = new javax.swing.JTextField();
        pnl_container2 = new javax.swing.JPanel();
        lbl_productType = new javax.swing.JLabel();
        cmb_productType = new javax.swing.JComboBox<>();
        pnl_control = new javax.swing.JPanel();
        pnl_btnGroup = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_viewSaves = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        btn_promotion = new javax.swing.JButton();
        pnl_productDetail = new javax.swing.JPanel();
        pnl_productTop1 = new javax.swing.JPanel();
        pnl_productTopLeft1 = new javax.swing.JPanel();
        lbl_productImg1 = new javax.swing.JLabel();
        pnl_productTopRight1 = new javax.swing.JPanel();
        pnl_orderId1 = new javax.swing.JPanel();
        pnl_container7 = new javax.swing.JPanel();
        lbl_productId1 = new javax.swing.JLabel();
        txt_productId1 = new javax.swing.JTextField();
        pnl_container8 = new javax.swing.JPanel();
        lbl_productName1 = new javax.swing.JLabel();
        scr_productName1 = new javax.swing.JScrollPane();
        txa_productName1 = new javax.swing.JTextArea();
        pnl_productCenter1 = new javax.swing.JPanel();
        pnl_container9 = new javax.swing.JPanel();
        lbl_productCostPrice1 = new javax.swing.JLabel();
        txt_productCostPrice1 = new javax.swing.JTextField();
        pnl_container10 = new javax.swing.JPanel();
        lbl_productPrice1 = new javax.swing.JLabel();
        txt_productPrice1 = new javax.swing.JTextField();
        pnl_container11 = new javax.swing.JPanel();
        lbl_productInventory1 = new javax.swing.JLabel();
        txt_productInventory1 = new javax.swing.JTextField();
        pnl_container12 = new javax.swing.JPanel();
        lbl_productVAT1 = new javax.swing.JLabel();
        txt_productVAT1 = new javax.swing.JTextField();
        pnl_container13 = new javax.swing.JPanel();
        lbl_productType1 = new javax.swing.JLabel();
        cmb_productType1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        splitPane_main.setMinimumSize(new java.awt.Dimension(1305, 768));

        pnl_left.setMinimumSize(new java.awt.Dimension(700, 59));
        pnl_left.setPreferredSize(new java.awt.Dimension(900, 768));
        pnl_left.setLayout(new java.awt.BorderLayout());

        pnl_header.setPreferredSize(new java.awt.Dimension(1366, 50));
        pnl_header.setLayout(new javax.swing.BoxLayout(pnl_header, javax.swing.BoxLayout.LINE_AXIS));

        txt_search.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã sản phẩm");
        pnl_header.add(txt_search);

        btn_search.setText("Thêm");
        btn_search.setMaximumSize(new java.awt.Dimension(100, 50));
        btn_search.setMinimumSize(new java.awt.Dimension(100, 50));
        btn_search.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_search.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        pnl_header.add(btn_search);

        pnl_left.add(pnl_header, java.awt.BorderLayout.NORTH);

        pnl_cart.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_cart.setLayout(new java.awt.BorderLayout());

        tbl_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SP0001", "Thiên tài bên trái, kẻ điên bên phải", "1", "100000", "100000"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        scr_cart.setViewportView(tbl_cart);

        pnl_cart.add(scr_cart, java.awt.BorderLayout.CENTER);

        pnl_cartFooter.setPreferredSize(new java.awt.Dimension(800, 60));
        pnl_cartFooter.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Tổng tiền");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnl_cartFooter.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnl_cart.add(pnl_cartFooter, java.awt.BorderLayout.PAGE_END);

        pnl_left.add(pnl_cart, java.awt.BorderLayout.CENTER);

        splitPane_main.setLeftComponent(pnl_left);

        pnl_right.setPreferredSize(new java.awt.Dimension(400, 768));
        pnl_right.setLayout(new javax.swing.BoxLayout(pnl_right, javax.swing.BoxLayout.Y_AXIS));

        pnl_productInfo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_productInfo.setPreferredSize(new java.awt.Dimension(400, 400));
        pnl_productInfo.setLayout(new javax.swing.BoxLayout(pnl_productInfo, javax.swing.BoxLayout.Y_AXIS));

        pnl_productTop.setMinimumSize(new java.awt.Dimension(400, 180));
        pnl_productTop.setPreferredSize(new java.awt.Dimension(400, 180));
        pnl_productTop.setLayout(new java.awt.GridLayout(1, 0));

        pnl_productTopLeft.setLayout(new java.awt.GridLayout(1, 0));

        lbl_productImg.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;");
        lbl_productImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_productImg.setText("Hình ảnh sản phẩm");
        pnl_productTopLeft.add(lbl_productImg);

        pnl_productTop.add(pnl_productTopLeft);

        pnl_productTopRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_productTopRight.setMinimumSize(new java.awt.Dimension(300, 132));
        pnl_productTopRight.setPreferredSize(new java.awt.Dimension(200, 100));
        pnl_productTopRight.setLayout(new java.awt.BorderLayout());

        pnl_orderId.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_orderId.setLayout(new javax.swing.BoxLayout(pnl_orderId, javax.swing.BoxLayout.Y_AXIS));

        pnl_container.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_container.setLayout(new javax.swing.BoxLayout(pnl_container, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productId.setText("Mã sản phẩm");
        lbl_productId.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_container.add(lbl_productId);

        txt_productId.setText(" SP01221232");
        pnl_container.add(txt_productId);

        pnl_orderId.add(pnl_container);

        pnl_container1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        pnl_container1.setMinimumSize(new java.awt.Dimension(200, 110));
        pnl_container1.setPreferredSize(new java.awt.Dimension(279, 140));
        pnl_container1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lbl_productName.setText("Tên sản phẩm");
        lbl_productName.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_container1.add(lbl_productName);

        scr_productName.setMinimumSize(new java.awt.Dimension(100, 100));

        txa_productName.setColumns(15);
        txa_productName.setLineWrap(true);
        txa_productName.setRows(4);
        txa_productName.setTabSize(4);
        txa_productName.setText("Cuộc đời của thanhcanhit");
        scr_productName.setViewportView(txa_productName);

        pnl_container1.add(scr_productName);

        pnl_orderId.add(pnl_container1);

        pnl_productTopRight.add(pnl_orderId, java.awt.BorderLayout.CENTER);

        pnl_productTop.add(pnl_productTopRight);

        pnl_productInfo.add(pnl_productTop);

        pnl_productCenter.setLayout(new javax.swing.BoxLayout(pnl_productCenter, javax.swing.BoxLayout.Y_AXIS));

        pnl_container3.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container3.setLayout(new javax.swing.BoxLayout(pnl_container3, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productCostPrice.setText("Giá nhập");
        lbl_productCostPrice.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container3.add(lbl_productCostPrice);

        txt_productCostPrice.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productCostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productCostPriceActionPerformed(evt);
            }
        });
        pnl_container3.add(txt_productCostPrice);

        pnl_productCenter.add(pnl_container3);

        pnl_container4.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container4.setLayout(new javax.swing.BoxLayout(pnl_container4, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productPrice.setText("Giá bán");
        lbl_productPrice.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container4.add(lbl_productPrice);

        txt_productPrice.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productPriceActionPerformed(evt);
            }
        });
        pnl_container4.add(txt_productPrice);

        pnl_productCenter.add(pnl_container4);

        pnl_container5.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container5.setLayout(new javax.swing.BoxLayout(pnl_container5, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productInventory.setText("Tồn kho");
        lbl_productInventory.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container5.add(lbl_productInventory);

        txt_productInventory.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productInventoryActionPerformed(evt);
            }
        });
        pnl_container5.add(txt_productInventory);

        pnl_productCenter.add(pnl_container5);

        pnl_container6.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container6.setLayout(new javax.swing.BoxLayout(pnl_container6, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productVAT.setText("VAT");
        lbl_productVAT.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container6.add(lbl_productVAT);

        txt_productVAT.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productVATActionPerformed(evt);
            }
        });
        pnl_container6.add(txt_productVAT);

        pnl_productCenter.add(pnl_container6);

        pnl_container2.setLayout(new javax.swing.BoxLayout(pnl_container2, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productType.setText("Loại sản phẩm");
        lbl_productType.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container2.add(lbl_productType);

        cmb_productType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Văn phòng phẩm" }));
        pnl_container2.add(cmb_productType);

        pnl_productCenter.add(pnl_container2);

        pnl_productInfo.add(pnl_productCenter);

        pnl_right.add(pnl_productInfo);

        pnl_control.setLayout(new javax.swing.BoxLayout(pnl_control, javax.swing.BoxLayout.PAGE_AXIS));

        pnl_btnGroup.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_btnGroup.setPreferredSize(new java.awt.Dimension(281, 100));
        pnl_btnGroup.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btn_save.setText("LƯU TẠM");
        pnl_btnGroup.add(btn_save);

        btn_viewSaves.setText("XỨ LÍ ĐƠN LƯU TẠM");
        pnl_btnGroup.add(btn_viewSaves);

        btn_cancle.setText("HỦY");
        pnl_btnGroup.add(btn_cancle);

        btn_promotion.setText("KHUYẾN MÃI");
        pnl_btnGroup.add(btn_promotion);

        pnl_control.add(pnl_btnGroup);

        pnl_right.add(pnl_control);

        pnl_productDetail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_productDetail.setPreferredSize(new java.awt.Dimension(400, 400));
        pnl_productDetail.setLayout(new javax.swing.BoxLayout(pnl_productDetail, javax.swing.BoxLayout.Y_AXIS));

        pnl_productTop1.setMinimumSize(new java.awt.Dimension(400, 180));
        pnl_productTop1.setPreferredSize(new java.awt.Dimension(400, 180));
        pnl_productTop1.setLayout(new java.awt.GridLayout());

        pnl_productTopLeft1.setLayout(new java.awt.GridLayout());

        lbl_productImg.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;");
        lbl_productImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_productImg1.setText("Hình ảnh sản phẩm");
        pnl_productTopLeft1.add(lbl_productImg1);

        pnl_productTop1.add(pnl_productTopLeft1);

        pnl_productTopRight1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        pnl_productTopRight1.setMinimumSize(new java.awt.Dimension(300, 132));
        pnl_productTopRight1.setPreferredSize(new java.awt.Dimension(200, 100));
        pnl_productTopRight1.setLayout(new java.awt.BorderLayout());

        pnl_orderId1.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_orderId1.setLayout(new javax.swing.BoxLayout(pnl_orderId1, javax.swing.BoxLayout.Y_AXIS));

        pnl_container7.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_container7.setLayout(new javax.swing.BoxLayout(pnl_container7, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productId1.setText("Mã sản phẩm");
        lbl_productId1.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_container7.add(lbl_productId1);

        txt_productId1.setText(" SP01221232");
        pnl_container7.add(txt_productId1);

        pnl_orderId1.add(pnl_container7);

        pnl_container8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        pnl_container8.setMinimumSize(new java.awt.Dimension(200, 110));
        pnl_container8.setPreferredSize(new java.awt.Dimension(279, 140));
        pnl_container8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lbl_productName1.setText("Tên sản phẩm");
        lbl_productName1.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_container8.add(lbl_productName1);

        scr_productName1.setMinimumSize(new java.awt.Dimension(100, 100));

        txa_productName1.setColumns(15);
        txa_productName1.setLineWrap(true);
        txa_productName1.setRows(4);
        txa_productName1.setTabSize(4);
        txa_productName1.setText("Cuộc đời của thanhcanhit");
        scr_productName1.setViewportView(txa_productName1);

        pnl_container8.add(scr_productName1);

        pnl_orderId1.add(pnl_container8);

        pnl_productTopRight1.add(pnl_orderId1, java.awt.BorderLayout.CENTER);

        pnl_productTop1.add(pnl_productTopRight1);

        pnl_productDetail.add(pnl_productTop1);

        pnl_productCenter1.setLayout(new javax.swing.BoxLayout(pnl_productCenter1, javax.swing.BoxLayout.Y_AXIS));

        pnl_container9.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container9.setLayout(new javax.swing.BoxLayout(pnl_container9, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productCostPrice1.setText("Giá nhập");
        lbl_productCostPrice1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container9.add(lbl_productCostPrice1);

        txt_productCostPrice1.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productCostPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productCostPrice1ActionPerformed(evt);
            }
        });
        pnl_container9.add(txt_productCostPrice1);

        pnl_productCenter1.add(pnl_container9);

        pnl_container10.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container10.setLayout(new javax.swing.BoxLayout(pnl_container10, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productPrice1.setText("Giá bán");
        lbl_productPrice1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container10.add(lbl_productPrice1);

        txt_productPrice1.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productPrice1ActionPerformed(evt);
            }
        });
        pnl_container10.add(txt_productPrice1);

        pnl_productCenter1.add(pnl_container10);

        pnl_container11.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container11.setLayout(new javax.swing.BoxLayout(pnl_container11, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productInventory1.setText("Tồn kho");
        lbl_productInventory1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container11.add(lbl_productInventory1);

        txt_productInventory1.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productInventory1ActionPerformed(evt);
            }
        });
        pnl_container11.add(txt_productInventory1);

        pnl_productCenter1.add(pnl_container11);

        pnl_container12.setPreferredSize(new java.awt.Dimension(561, 40));
        pnl_container12.setLayout(new javax.swing.BoxLayout(pnl_container12, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productVAT1.setText("VAT");
        lbl_productVAT1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container12.add(lbl_productVAT1);

        txt_productVAT1.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_productVAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productVAT1ActionPerformed(evt);
            }
        });
        pnl_container12.add(txt_productVAT1);

        pnl_productCenter1.add(pnl_container12);

        pnl_container13.setLayout(new javax.swing.BoxLayout(pnl_container13, javax.swing.BoxLayout.LINE_AXIS));

        lbl_productType1.setText("Loại sản phẩm");
        lbl_productType1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_container13.add(lbl_productType1);

        cmb_productType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Văn phòng phẩm" }));
        pnl_container13.add(cmb_productType1);

        pnl_productCenter1.add(pnl_container13);

        pnl_productDetail.add(pnl_productCenter1);

        pnl_right.add(pnl_productDetail);

        splitPane_main.setRightComponent(pnl_right);

        add(splitPane_main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_productCostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productCostPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productCostPriceActionPerformed

    private void txt_productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productPriceActionPerformed

    private void txt_productInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productInventoryActionPerformed

    private void txt_productVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productVATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productVATActionPerformed

    private void txt_productCostPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productCostPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productCostPrice1ActionPerformed

    private void txt_productPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productPrice1ActionPerformed

    private void txt_productInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productInventory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productInventory1ActionPerformed

    private void txt_productVAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productVAT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productVAT1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_promotion;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_viewSaves;
    private javax.swing.JComboBox<String> cmb_productType;
    private javax.swing.JComboBox<String> cmb_productType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_productCostPrice;
    private javax.swing.JLabel lbl_productCostPrice1;
    private javax.swing.JLabel lbl_productId;
    private javax.swing.JLabel lbl_productId1;
    private javax.swing.JLabel lbl_productImg;
    private javax.swing.JLabel lbl_productImg1;
    private javax.swing.JLabel lbl_productInventory;
    private javax.swing.JLabel lbl_productInventory1;
    private javax.swing.JLabel lbl_productName;
    private javax.swing.JLabel lbl_productName1;
    private javax.swing.JLabel lbl_productPrice;
    private javax.swing.JLabel lbl_productPrice1;
    private javax.swing.JLabel lbl_productType;
    private javax.swing.JLabel lbl_productType1;
    private javax.swing.JLabel lbl_productVAT;
    private javax.swing.JLabel lbl_productVAT1;
    private javax.swing.JPanel pnl_btnGroup;
    private javax.swing.JPanel pnl_cart;
    private javax.swing.JPanel pnl_cartFooter;
    private javax.swing.JPanel pnl_container;
    private javax.swing.JPanel pnl_container1;
    private javax.swing.JPanel pnl_container10;
    private javax.swing.JPanel pnl_container11;
    private javax.swing.JPanel pnl_container12;
    private javax.swing.JPanel pnl_container13;
    private javax.swing.JPanel pnl_container2;
    private javax.swing.JPanel pnl_container3;
    private javax.swing.JPanel pnl_container4;
    private javax.swing.JPanel pnl_container5;
    private javax.swing.JPanel pnl_container6;
    private javax.swing.JPanel pnl_container7;
    private javax.swing.JPanel pnl_container8;
    private javax.swing.JPanel pnl_container9;
    private javax.swing.JPanel pnl_control;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_left;
    private javax.swing.JPanel pnl_orderId;
    private javax.swing.JPanel pnl_orderId1;
    private javax.swing.JPanel pnl_productCenter;
    private javax.swing.JPanel pnl_productCenter1;
    private javax.swing.JPanel pnl_productDetail;
    private javax.swing.JPanel pnl_productInfo;
    private javax.swing.JPanel pnl_productTop;
    private javax.swing.JPanel pnl_productTop1;
    private javax.swing.JPanel pnl_productTopLeft;
    private javax.swing.JPanel pnl_productTopLeft1;
    private javax.swing.JPanel pnl_productTopRight;
    private javax.swing.JPanel pnl_productTopRight1;
    private javax.swing.JPanel pnl_right;
    private javax.swing.JScrollPane scr_cart;
    private javax.swing.JScrollPane scr_productName;
    private javax.swing.JScrollPane scr_productName1;
    private javax.swing.JSplitPane splitPane_main;
    private javax.swing.JTable tbl_cart;
    private javax.swing.JTextArea txa_productName;
    private javax.swing.JTextArea txa_productName1;
    private javax.swing.JTextField txt_productCostPrice;
    private javax.swing.JTextField txt_productCostPrice1;
    private javax.swing.JTextField txt_productId;
    private javax.swing.JTextField txt_productId1;
    private javax.swing.JTextField txt_productInventory;
    private javax.swing.JTextField txt_productInventory1;
    private javax.swing.JTextField txt_productPrice;
    private javax.swing.JTextField txt_productPrice1;
    private javax.swing.JTextField txt_productVAT;
    private javax.swing.JTextField txt_productVAT1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
