/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.PromotionManagament_BUS;
import com.formdev.flatlaf.FlatClientProperties;
import entity.Promotion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Như Tâm
 */
public class PromotionManagement_GUI extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form PromotionManagement_GUI
     */
    private PromotionManagament_BUS bus;
    private Promotion currentPromotion = null;
    //Model
    private DefaultTableModel tblModel_promotion;
    private DefaultComboBoxModel cmbModel_type;
    private DefaultComboBoxModel cmbModel_status;

    public PromotionManagement_GUI() {
        initComponents();
        init();
    }

    private void init() {
        bus = new PromotionManagament_BUS();
        //model
        tblModel_promotion = new DefaultTableModel(new String[]{"Mã khuyến mãi", "Loại", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"}, 0);
        tbl_inforPromo.setModel(tblModel_promotion);
        tbl_inforPromo.getSelectionModel().addListSelectionListener((e) -> {
            int rowIndex = tbl_inforPromo.getSelectedRow();
            if(rowIndex == -1)
                return;
            
            String promotionID = tblModel_promotion.getValueAt(rowIndex, 0).toString();
            this.currentPromotion = bus.getPromotion(promotionID);
            renderCurrentPromotion();
        });
        //combobox
        cmbModel_type = new DefaultComboBoxModel(new String[] {"Loại", "Số tiền", "Phần trăm"});
        cmb_typePromo.setModel(cmbModel_type);
        cmbModel_status = new DefaultComboBoxModel(new String[] {"Trạng thái", "Đang diễn ra", "Đã kết thúc"});
        cmb_statusPromo.setModel(cmbModel_status);
        
        
        renderPromotionTables(bus.getALLPromotion());
        
        
        
        
        
        
    }
    private void renderCurrentPromotion() {
        txt_promotionID.setText(currentPromotion.getPromotionID());
        if(currentPromotion.getType().getValue() == 1)
            rdb_price.setSelected(true);
        else
            rdb_percent.setSelected(true);
        txt_discountPromo.setText(currentPromotion.getDiscount() + "");
        txt_startDatePromo.setText(currentPromotion.getStartedDate().toString());
        txt_endDatePromo.setText(currentPromotion.getEndedDate().toString());
    }
    
    private void renderPromotionTables(ArrayList<Promotion> promotionList) {
        tblModel_promotion.setRowCount(0);
        String status, type;
        for (Promotion promotion : promotionList) {
            if(promotion.getEndedDate().after(java.sql.Date.valueOf(LocalDate.now())))
                status = "Còn hạn";
            else 
                status = "Hết hạn";
            if(promotion.getType().getValue() == 1)
                type = "Tiền";
            else
                type = "Phần trăm";
            String[] newRow = {promotion.getPromotionID(), type, promotion.getStartedDate().toString(), promotion.getEndedDate().toString(), status};
            tblModel_promotion.addRow(newRow);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_typePromo = new javax.swing.ButtonGroup();
        pnl_searchPromotion = new javax.swing.JPanel();
        pnl_txtSearchPromo = new javax.swing.JPanel();
        txt_searchPromo = new javax.swing.JTextField();
        pnl_buttonSearchPromo = new javax.swing.JPanel();
        btn_searchPromo = new javax.swing.JButton();
        pnl_filterPromo = new javax.swing.JPanel();
        cmb_typePromo = new javax.swing.JComboBox<>();
        cmb_statusPromo = new javax.swing.JComboBox<>();
        slp_promotion = new javax.swing.JSplitPane();
        pnl_listPromotion = new javax.swing.JPanel();
        pnl_promotionInfor = new javax.swing.JPanel();
        src_inforPromo = new javax.swing.JScrollPane();
        tbl_inforPromo = new javax.swing.JTable();
        pnl_promotionNew = new javax.swing.JPanel();
        pnl_inforPromo = new javax.swing.JPanel();
        pnl_txtInforPromo = new javax.swing.JPanel();
        pnl_promoID = new javax.swing.JPanel();
        lbl_promotionID = new javax.swing.JLabel();
        txt_promotionID = new javax.swing.JTextField();
        pnl_typePromo = new javax.swing.JPanel();
        lbl_typePromo = new javax.swing.JLabel();
        pnl_rdbTypePromo = new javax.swing.JPanel();
        rdb_percent = new javax.swing.JRadioButton();
        rdb_price = new javax.swing.JRadioButton();
        pnl_discountPromo = new javax.swing.JPanel();
        lbl_discountPromo = new javax.swing.JLabel();
        txt_discountPromo = new javax.swing.JTextField();
        pnl_startDatePromo = new javax.swing.JPanel();
        lbl_startDatePromo = new javax.swing.JLabel();
        txt_startDatePromo = new javax.swing.JTextField();
        pnl_endDatePromo = new javax.swing.JPanel();
        lbl_endDatePromo = new javax.swing.JLabel();
        txt_endDatePromo = new javax.swing.JTextField();
        pnl_buttonPromo = new javax.swing.JPanel();
        pnl_btnCreatePromo = new javax.swing.JPanel();
        btn_createPromo = new javax.swing.JButton();
        pnl_btnRemovePromo = new javax.swing.JPanel();
        btn_removePromo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_searchPromotion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_searchPromotion.setMaximumSize(new java.awt.Dimension(900, 50));
        pnl_searchPromotion.setMinimumSize(new java.awt.Dimension(500, 27));
        pnl_searchPromotion.setPreferredSize(new java.awt.Dimension(700, 50));
        pnl_searchPromotion.setLayout(new javax.swing.BoxLayout(pnl_searchPromotion, javax.swing.BoxLayout.X_AXIS));

        pnl_txtSearchPromo.setLayout(new javax.swing.BoxLayout(pnl_txtSearchPromo, javax.swing.BoxLayout.LINE_AXIS));

        txt_searchPromo.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã khuyến mãi");
        pnl_txtSearchPromo.add(txt_searchPromo);

        pnl_searchPromotion.add(pnl_txtSearchPromo);

        pnl_buttonSearchPromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnl_buttonSearchPromo.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        pnl_buttonSearchPromo.setPreferredSize(new java.awt.Dimension(100, 23));
        pnl_buttonSearchPromo.setLayout(new java.awt.BorderLayout());

        btn_searchPromo.setText("Tìm kiếm");
        btn_searchPromo.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_searchPromo.setMaximumSize(new java.awt.Dimension(39, 23));
        btn_searchPromo.setMinimumSize(new java.awt.Dimension(39, 23));
        btn_searchPromo.setPreferredSize(new java.awt.Dimension(39, 23));
        pnl_buttonSearchPromo.add(btn_searchPromo, java.awt.BorderLayout.CENTER);

        pnl_searchPromotion.add(pnl_buttonSearchPromo);

        pnl_filterPromo.setMaximumSize(new java.awt.Dimension(500, 50));
        pnl_filterPromo.setMinimumSize(new java.awt.Dimension(300, 32));
        pnl_filterPromo.setPreferredSize(new java.awt.Dimension(400, 50));
        pnl_filterPromo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cmb_typePromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại" }));
        pnl_filterPromo.add(cmb_typePromo);

        cmb_statusPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Đang diễn ra", "Đã kết thúc" }));
        pnl_filterPromo.add(cmb_statusPromo);

        pnl_searchPromotion.add(pnl_filterPromo);

        add(pnl_searchPromotion, java.awt.BorderLayout.NORTH);

        pnl_listPromotion.setMaximumSize(new java.awt.Dimension(1000, 2147483647));
        pnl_listPromotion.setPreferredSize(new java.awt.Dimension(800, 432));
        pnl_listPromotion.setLayout(new java.awt.BorderLayout());

        pnl_promotionInfor.setMaximumSize(new java.awt.Dimension(900, 2147483647));
        pnl_promotionInfor.setMinimumSize(new java.awt.Dimension(700, 16));
        pnl_promotionInfor.setPreferredSize(new java.awt.Dimension(700, 402));
        pnl_promotionInfor.setLayout(new java.awt.BorderLayout());

        src_inforPromo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        tbl_inforPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Loại KM", "Giảm giá", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        src_inforPromo.setViewportView(tbl_inforPromo);

        pnl_promotionInfor.add(src_inforPromo, java.awt.BorderLayout.CENTER);

        pnl_listPromotion.add(pnl_promotionInfor, java.awt.BorderLayout.CENTER);

        slp_promotion.setLeftComponent(pnl_listPromotion);

        pnl_promotionNew.setAlignmentX(0.0F);
        pnl_promotionNew.setAlignmentY(0.0F);
        pnl_promotionNew.setMaximumSize(new java.awt.Dimension(366, 32767));
        pnl_promotionNew.setMinimumSize(new java.awt.Dimension(300, 192));
        pnl_promotionNew.setPreferredSize(new java.awt.Dimension(300, 190));
        pnl_promotionNew.setLayout(new javax.swing.BoxLayout(pnl_promotionNew, javax.swing.BoxLayout.Y_AXIS));

        pnl_inforPromo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_inforPromo.setMinimumSize(new java.awt.Dimension(300, 263));
        pnl_inforPromo.setLayout(new java.awt.BorderLayout());

        pnl_txtInforPromo.setLayout(new javax.swing.BoxLayout(pnl_txtInforPromo, javax.swing.BoxLayout.Y_AXIS));

        pnl_promoID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_promoID.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_promoID.setMinimumSize(new java.awt.Dimension(151, 20));
        pnl_promoID.setPreferredSize(new java.awt.Dimension(176, 40));
        pnl_promoID.setLayout(new javax.swing.BoxLayout(pnl_promoID, javax.swing.BoxLayout.X_AXIS));

        lbl_promotionID.setText("Mã KM:");
        lbl_promotionID.setMaximumSize(new java.awt.Dimension(95, 16));
        lbl_promotionID.setMinimumSize(new java.awt.Dimension(77, 16));
        lbl_promotionID.setPreferredSize(new java.awt.Dimension(95, 16));
        pnl_promoID.add(lbl_promotionID);

        txt_promotionID.setEditable(false);
        txt_promotionID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_promotionID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_promotionID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_promotionID.setPreferredSize(new java.awt.Dimension(71, 30));
        txt_promotionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_promotionIDActionPerformed(evt);
            }
        });
        pnl_promoID.add(txt_promotionID);

        pnl_txtInforPromo.add(pnl_promoID);

        pnl_typePromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_typePromo.setLayout(new javax.swing.BoxLayout(pnl_typePromo, javax.swing.BoxLayout.X_AXIS));

        lbl_typePromo.setText("Loại KM:");
        lbl_typePromo.setMaximumSize(new java.awt.Dimension(95, 16));
        lbl_typePromo.setMinimumSize(new java.awt.Dimension(77, 16));
        lbl_typePromo.setPreferredSize(new java.awt.Dimension(95, 16));
        pnl_typePromo.add(lbl_typePromo);

        pnl_rdbTypePromo.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnl_rdbTypePromo.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_rdbTypePromo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        group_typePromo.add(rdb_percent);
        rdb_percent.setText("Phần trăm");
        pnl_rdbTypePromo.add(rdb_percent);

        group_typePromo.add(rdb_price);
        rdb_price.setText("Tiền");
        rdb_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_priceActionPerformed(evt);
            }
        });
        pnl_rdbTypePromo.add(rdb_price);

        pnl_typePromo.add(pnl_rdbTypePromo);

        pnl_txtInforPromo.add(pnl_typePromo);

        pnl_discountPromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_discountPromo.setLayout(new javax.swing.BoxLayout(pnl_discountPromo, javax.swing.BoxLayout.X_AXIS));

        lbl_discountPromo.setText("Giảm giá:");
        lbl_discountPromo.setMaximumSize(new java.awt.Dimension(95, 16));
        lbl_discountPromo.setMinimumSize(new java.awt.Dimension(77, 16));
        lbl_discountPromo.setPreferredSize(new java.awt.Dimension(95, 16));
        pnl_discountPromo.add(lbl_discountPromo);

        txt_discountPromo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_discountPromo.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_discountPromo.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_discountPromo.add(txt_discountPromo);

        pnl_txtInforPromo.add(pnl_discountPromo);

        pnl_startDatePromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_startDatePromo.setLayout(new javax.swing.BoxLayout(pnl_startDatePromo, javax.swing.BoxLayout.X_AXIS));

        lbl_startDatePromo.setText("Ngày bắt đầu:");
        lbl_startDatePromo.setMaximumSize(new java.awt.Dimension(95, 16));
        lbl_startDatePromo.setMinimumSize(new java.awt.Dimension(77, 16));
        lbl_startDatePromo.setPreferredSize(new java.awt.Dimension(95, 16));
        pnl_startDatePromo.add(lbl_startDatePromo);

        txt_startDatePromo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_startDatePromo.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_startDatePromo.setPreferredSize(new java.awt.Dimension(64, 30));
        txt_startDatePromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_startDatePromoActionPerformed(evt);
            }
        });
        pnl_startDatePromo.add(txt_startDatePromo);

        pnl_txtInforPromo.add(pnl_startDatePromo);

        pnl_endDatePromo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_endDatePromo.setLayout(new javax.swing.BoxLayout(pnl_endDatePromo, javax.swing.BoxLayout.X_AXIS));

        lbl_endDatePromo.setText("Ngày kết thúc:");
        pnl_endDatePromo.add(lbl_endDatePromo);

        txt_endDatePromo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_endDatePromo.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_endDatePromo.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_endDatePromo.add(txt_endDatePromo);

        pnl_txtInforPromo.add(pnl_endDatePromo);

        pnl_inforPromo.add(pnl_txtInforPromo, java.awt.BorderLayout.CENTER);

        pnl_buttonPromo.setMinimumSize(new java.awt.Dimension(100, 50));
        pnl_buttonPromo.setPreferredSize(new java.awt.Dimension(1261, 50));
        pnl_buttonPromo.setLayout(new javax.swing.BoxLayout(pnl_buttonPromo, javax.swing.BoxLayout.LINE_AXIS));

        pnl_btnCreatePromo.setLayout(new java.awt.BorderLayout());

        btn_createPromo.setText("TẠO MỚI");
        btn_createPromo.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        pnl_btnCreatePromo.add(btn_createPromo, java.awt.BorderLayout.CENTER);

        pnl_buttonPromo.add(pnl_btnCreatePromo);

        pnl_btnRemovePromo.setLayout(new java.awt.BorderLayout());

        btn_removePromo.setText("GỠ ");
        btn_removePromo.setActionCommand("");
        btn_removePromo.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_removePromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePromoActionPerformed(evt);
            }
        });
        pnl_btnRemovePromo.add(btn_removePromo, java.awt.BorderLayout.CENTER);

        pnl_buttonPromo.add(pnl_btnRemovePromo);

        pnl_inforPromo.add(pnl_buttonPromo, java.awt.BorderLayout.SOUTH);

        pnl_promotionNew.add(pnl_inforPromo);

        slp_promotion.setRightComponent(pnl_promotionNew);

        add(slp_promotion, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removePromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removePromoActionPerformed

    private void txt_startDatePromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_startDatePromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_startDatePromoActionPerformed

    private void txt_promotionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_promotionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_promotionIDActionPerformed

    private void rdb_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_priceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createPromo;
    private javax.swing.JButton btn_removePromo;
    private javax.swing.JButton btn_searchPromo;
    private javax.swing.JComboBox<String> cmb_statusPromo;
    private javax.swing.JComboBox<String> cmb_typePromo;
    private javax.swing.ButtonGroup group_typePromo;
    private javax.swing.JLabel lbl_discountPromo;
    private javax.swing.JLabel lbl_endDatePromo;
    private javax.swing.JLabel lbl_promotionID;
    private javax.swing.JLabel lbl_startDatePromo;
    private javax.swing.JLabel lbl_typePromo;
    private javax.swing.JPanel pnl_btnCreatePromo;
    private javax.swing.JPanel pnl_btnRemovePromo;
    private javax.swing.JPanel pnl_buttonPromo;
    private javax.swing.JPanel pnl_buttonSearchPromo;
    private javax.swing.JPanel pnl_discountPromo;
    private javax.swing.JPanel pnl_endDatePromo;
    private javax.swing.JPanel pnl_filterPromo;
    private javax.swing.JPanel pnl_inforPromo;
    private javax.swing.JPanel pnl_listPromotion;
    private javax.swing.JPanel pnl_promoID;
    private javax.swing.JPanel pnl_promotionInfor;
    private javax.swing.JPanel pnl_promotionNew;
    private javax.swing.JPanel pnl_rdbTypePromo;
    private javax.swing.JPanel pnl_searchPromotion;
    private javax.swing.JPanel pnl_startDatePromo;
    private javax.swing.JPanel pnl_txtInforPromo;
    private javax.swing.JPanel pnl_txtSearchPromo;
    private javax.swing.JPanel pnl_typePromo;
    private javax.swing.JRadioButton rdb_percent;
    private javax.swing.JRadioButton rdb_price;
    private javax.swing.JSplitPane slp_promotion;
    private javax.swing.JScrollPane src_inforPromo;
    private javax.swing.JTable tbl_inforPromo;
    private javax.swing.JTextField txt_discountPromo;
    private javax.swing.JTextField txt_endDatePromo;
    private javax.swing.JTextField txt_promotionID;
    private javax.swing.JTextField txt_searchPromo;
    private javax.swing.JTextField txt_startDatePromo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

}
