/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Như Tâm
 */
public class ReturnOrderManagemant_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ReturnOrderManagemant_GUI
     */
    public ReturnOrderManagemant_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_topReturnOrder = new javax.swing.JPanel();
        pnl_searchRerturnOrder = new javax.swing.JPanel();
        txt_searchReturnOrder = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btb_searchReturnOrder = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        chk_admitReturnOrder = new javax.swing.JCheckBox();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        chk_denyReturnOrder = new javax.swing.JCheckBox();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        btn_pendingReturnOrder = new javax.swing.JCheckBox();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_topReturnOrder.setPreferredSize(new java.awt.Dimension(1368, 80));
        pnl_topReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_topReturnOrder, javax.swing.BoxLayout.LINE_AXIS));

        pnl_searchRerturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 28));

        txt_searchReturnOrder.setPreferredSize(new java.awt.Dimension(300, 22));
        pnl_searchRerturnOrder.add(txt_searchReturnOrder);

        pnl_topReturnOrder.add(pnl_searchRerturnOrder);
        pnl_topReturnOrder.add(filler1);

        btb_searchReturnOrder.setText("Tìm kiếm");
        pnl_topReturnOrder.add(btb_searchReturnOrder);
        pnl_topReturnOrder.add(filler2);

        chk_admitReturnOrder.setText("Đã chấp nhập");
        pnl_topReturnOrder.add(chk_admitReturnOrder);
        pnl_topReturnOrder.add(filler3);

        chk_denyReturnOrder.setText("Từ chối");
        pnl_topReturnOrder.add(chk_denyReturnOrder);
        pnl_topReturnOrder.add(filler4);

        btn_pendingReturnOrder.setText("Đang chờ");
        pnl_topReturnOrder.add(btn_pendingReturnOrder);
        pnl_topReturnOrder.add(filler5);

        add(pnl_topReturnOrder, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_searchReturnOrder;
    private javax.swing.JCheckBox btn_pendingReturnOrder;
    private javax.swing.JCheckBox chk_admitReturnOrder;
    private javax.swing.JCheckBox chk_denyReturnOrder;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel pnl_searchRerturnOrder;
    private javax.swing.JPanel pnl_topReturnOrder;
    private javax.swing.JTextField txt_searchReturnOrder;
    // End of variables declaration//GEN-END:variables
}
