/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Như Tâm
 */
public class ReturnOrderManagemant_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ReturnOrderManagemant_GUI
     */
    public ReturnOrderManagemant_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_topReturnOrder = new javax.swing.JPanel();
        pnl_searchRerturnOrder = new javax.swing.JPanel();
        txt_searchReturnOrder = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btb_searchReturnOrder = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        chk_admitReturnOrder = new javax.swing.JCheckBox();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        chk_denyReturnOrder = new javax.swing.JCheckBox();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        btn_pendingReturnOrder = new javax.swing.JCheckBox();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        pnl_centerReturnOrder = new javax.swing.JPanel();
        scr_inforReturnOrder = new javax.swing.JScrollPane();
        tbl_inforReturnOrder = new javax.swing.JTable();
        pnl_eastReturnOrder = new javax.swing.JPanel();
        pnl_employeeID = new javax.swing.JPanel();
        lbl_employeeID = new javax.swing.JLabel();
        txt_employeeID = new javax.swing.JTextField();
        pnl_returnOrderID = new javax.swing.JPanel();
        lbl_returnOrderID = new javax.swing.JLabel();
        txt_returnOrderID = new javax.swing.JTextField();
        pnl_productID = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_statusReturnOrder = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        pnl_radioStatusReturnOrder = new javax.swing.JPanel();
        rdb_admit = new javax.swing.JRadioButton();
        rdb_deny = new javax.swing.JRadioButton();
        pnl_buttonSave = new javax.swing.JPanel();
        btn_saveReturnOrder = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_topReturnOrder.setPreferredSize(new java.awt.Dimension(1368, 80));
        pnl_topReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_topReturnOrder, javax.swing.BoxLayout.LINE_AXIS));

        pnl_searchRerturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 28));

        txt_searchReturnOrder.setPreferredSize(new java.awt.Dimension(300, 22));
        pnl_searchRerturnOrder.add(txt_searchReturnOrder);

        pnl_topReturnOrder.add(pnl_searchRerturnOrder);
        pnl_topReturnOrder.add(filler1);

        btb_searchReturnOrder.setText("Tìm kiếm");
        pnl_topReturnOrder.add(btb_searchReturnOrder);
        pnl_topReturnOrder.add(filler2);

        chk_admitReturnOrder.setText("Đã chấp nhập");
        pnl_topReturnOrder.add(chk_admitReturnOrder);
        pnl_topReturnOrder.add(filler3);

        chk_denyReturnOrder.setText("Từ chối");
        pnl_topReturnOrder.add(chk_denyReturnOrder);
        pnl_topReturnOrder.add(filler4);

        btn_pendingReturnOrder.setText("Đang chờ");
        pnl_topReturnOrder.add(btn_pendingReturnOrder);
        pnl_topReturnOrder.add(filler5);

        add(pnl_topReturnOrder, java.awt.BorderLayout.NORTH);

        pnl_centerReturnOrder.setLayout(new java.awt.BorderLayout());

        tbl_inforReturnOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HĐĐT", "Mã HĐ", "Ngày đổi", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scr_inforReturnOrder.setViewportView(tbl_inforReturnOrder);

        pnl_centerReturnOrder.add(scr_inforReturnOrder, java.awt.BorderLayout.CENTER);

        add(pnl_centerReturnOrder, java.awt.BorderLayout.CENTER);

        pnl_eastReturnOrder.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_eastReturnOrder.setPreferredSize(new java.awt.Dimension(400, 437));
        pnl_eastReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_eastReturnOrder, javax.swing.BoxLayout.Y_AXIS));

        pnl_employeeID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_employeeID.setPreferredSize(new java.awt.Dimension(132, 32));
        pnl_employeeID.setLayout(new javax.swing.BoxLayout(pnl_employeeID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_employeeID.setText("Mã NV:");
        lbl_employeeID.setPreferredSize(lbl_returnOrderID.getPreferredSize());
        pnl_employeeID.add(lbl_employeeID);
        pnl_employeeID.add(txt_employeeID);

        pnl_eastReturnOrder.add(pnl_employeeID);

        pnl_returnOrderID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_returnOrderID.setPreferredSize(new java.awt.Dimension(135, 32));
        pnl_returnOrderID.setLayout(new javax.swing.BoxLayout(pnl_returnOrderID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_returnOrderID.setText("Mã đơn ĐT:");
        pnl_returnOrderID.add(lbl_returnOrderID);
        pnl_returnOrderID.add(txt_returnOrderID);

        pnl_eastReturnOrder.add(pnl_returnOrderID);

        pnl_productID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_productID.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã SP", "Tên SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        pnl_productID.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_eastReturnOrder.add(pnl_productID);

        pnl_statusReturnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_statusReturnOrder.setMinimumSize(new java.awt.Dimension(135, 32));
        pnl_statusReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_statusReturnOrder, javax.swing.BoxLayout.LINE_AXIS));

        lbl_status.setText("Trạng thái:");
        lbl_status.setPreferredSize(lbl_returnOrderID.getPreferredSize());
        pnl_statusReturnOrder.add(lbl_status);
        lbl_status.getAccessibleContext().setAccessibleName("Trạng thái");

        pnl_radioStatusReturnOrder.setPreferredSize(new java.awt.Dimension(219, 12));
        pnl_radioStatusReturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 25));

        rdb_admit.setText("Xác nhận");
        pnl_radioStatusReturnOrder.add(rdb_admit);

        rdb_deny.setText("Từ chối");
        pnl_radioStatusReturnOrder.add(rdb_deny);

        pnl_statusReturnOrder.add(pnl_radioStatusReturnOrder);

        pnl_eastReturnOrder.add(pnl_statusReturnOrder);

        pnl_buttonSave.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btn_saveReturnOrder.setText("Lưu");
        btn_saveReturnOrder.setPreferredSize(new java.awt.Dimension(300, 40));
        pnl_buttonSave.add(btn_saveReturnOrder);

        pnl_eastReturnOrder.add(pnl_buttonSave);

        add(pnl_eastReturnOrder, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_searchReturnOrder;
    private javax.swing.JCheckBox btn_pendingReturnOrder;
    private javax.swing.JButton btn_saveReturnOrder;
    private javax.swing.JCheckBox chk_admitReturnOrder;
    private javax.swing.JCheckBox chk_denyReturnOrder;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_employeeID;
    private javax.swing.JLabel lbl_returnOrderID;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel pnl_buttonSave;
    private javax.swing.JPanel pnl_centerReturnOrder;
    private javax.swing.JPanel pnl_eastReturnOrder;
    private javax.swing.JPanel pnl_employeeID;
    private javax.swing.JPanel pnl_productID;
    private javax.swing.JPanel pnl_radioStatusReturnOrder;
    private javax.swing.JPanel pnl_returnOrderID;
    private javax.swing.JPanel pnl_searchRerturnOrder;
    private javax.swing.JPanel pnl_statusReturnOrder;
    private javax.swing.JPanel pnl_topReturnOrder;
    private javax.swing.JRadioButton rdb_admit;
    private javax.swing.JRadioButton rdb_deny;
    private javax.swing.JScrollPane scr_inforReturnOrder;
    private javax.swing.JTable tbl_inforReturnOrder;
    private javax.swing.JTextField txt_employeeID;
    private javax.swing.JTextField txt_returnOrderID;
    private javax.swing.JTextField txt_searchReturnOrder;
    // End of variables declaration//GEN-END:variables
}
