/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Như Tâm
 */
public class ReturnOrderManagemant_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ReturnOrderManagemant_GUI
     */
    public ReturnOrderManagemant_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_statusReturnOrder = new javax.swing.ButtonGroup();
        pnl_topReturnOrder = new javax.swing.JPanel();
        pnl_searchRerturnOrder = new javax.swing.JPanel();
        txt_searchReturnOrder = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btn_searchReturnOrder = new javax.swing.JButton();
        pnl_chkReturnOrder = new javax.swing.JPanel();
        chk_admitReturnOrder = new javax.swing.JCheckBox();
        chk_denyReturnOrder = new javax.swing.JCheckBox();
        chk_pendingReturnOrder = new javax.swing.JCheckBox();
        cmb_typeReturnOrder = new javax.swing.JComboBox<>();
        pnl_centerReturnOrder = new javax.swing.JPanel();
        scr_inforReturnOrder = new javax.swing.JScrollPane();
        tbl_inforReturnOrder = new javax.swing.JTable();
        pnl_eastReturnOrder = new javax.swing.JPanel();
        pnl_employeeID = new javax.swing.JPanel();
        lbl_employeeID = new javax.swing.JLabel();
        txt_employeeID = new javax.swing.JTextField();
        pnl_returnOrderID = new javax.swing.JPanel();
        lbl_returnOrderID = new javax.swing.JLabel();
        txt_returnOrderID = new javax.swing.JTextField();
        pnl_productID = new javax.swing.JPanel();
        lbl_product = new javax.swing.JLabel();
        scr_productInfor = new javax.swing.JScrollPane();
        tbl_productInfor = new javax.swing.JTable();
        pnl_statusReturnOrder = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        pnl_radioStatusReturnOrder = new javax.swing.JPanel();
        rdb_admit = new javax.swing.JRadioButton();
        rdb_deny = new javax.swing.JRadioButton();
        pnl_buttonSave = new javax.swing.JPanel();
        btn_saveReturnOrder = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_topReturnOrder.setPreferredSize(new java.awt.Dimension(1368, 60));
        pnl_topReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_topReturnOrder, javax.swing.BoxLayout.LINE_AXIS));

        pnl_searchRerturnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnl_searchRerturnOrder.setLayout(new javax.swing.BoxLayout(pnl_searchRerturnOrder, javax.swing.BoxLayout.X_AXIS));

        txt_searchReturnOrder.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã đơn đổi trả");
        txt_searchReturnOrder.setPreferredSize(new java.awt.Dimension(500, 22));
        pnl_searchRerturnOrder.add(txt_searchReturnOrder);
        pnl_searchRerturnOrder.add(filler6);

        btn_searchReturnOrder.setText("Tìm kiếm");
        btn_searchReturnOrder.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_searchReturnOrder.setMaximumSize(new java.awt.Dimension(79, 43));
        btn_searchReturnOrder.setPreferredSize(new java.awt.Dimension(90, 33));
        pnl_searchRerturnOrder.add(btn_searchReturnOrder);

        pnl_topReturnOrder.add(pnl_searchRerturnOrder);

        pnl_chkReturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 15));

        chk_admitReturnOrder.setText("Đã chấp nhập");
        pnl_chkReturnOrder.add(chk_admitReturnOrder);

        chk_denyReturnOrder.setText("Từ chối");
        pnl_chkReturnOrder.add(chk_denyReturnOrder);

        chk_pendingReturnOrder.setText("Đang chờ");
        pnl_chkReturnOrder.add(chk_pendingReturnOrder);

        cmb_typeReturnOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại đơn", "Đổi hàng", "Trả hàng" }));
        pnl_chkReturnOrder.add(cmb_typeReturnOrder);

        pnl_topReturnOrder.add(pnl_chkReturnOrder);

        add(pnl_topReturnOrder, java.awt.BorderLayout.NORTH);

        pnl_centerReturnOrder.setLayout(new java.awt.BorderLayout());

        tbl_inforReturnOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HĐĐT", "Mã HĐ", "Ngày đổi", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scr_inforReturnOrder.setViewportView(tbl_inforReturnOrder);

        pnl_centerReturnOrder.add(scr_inforReturnOrder, java.awt.BorderLayout.CENTER);

        add(pnl_centerReturnOrder, java.awt.BorderLayout.CENTER);

        pnl_eastReturnOrder.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnl_eastReturnOrder.setPreferredSize(new java.awt.Dimension(500, 437));
        pnl_eastReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_eastReturnOrder, javax.swing.BoxLayout.Y_AXIS));

        pnl_employeeID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_employeeID.setLayout(new javax.swing.BoxLayout(pnl_employeeID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_employeeID.setText("Mã nhân viên:");
        lbl_employeeID.setMaximumSize(new java.awt.Dimension(80, 16));
        lbl_employeeID.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_employeeID.add(lbl_employeeID);

        txt_employeeID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_employeeID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_employeeID.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_employeeID.add(txt_employeeID);

        pnl_eastReturnOrder.add(pnl_employeeID);

        pnl_returnOrderID.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_returnOrderID.setLayout(new javax.swing.BoxLayout(pnl_returnOrderID, javax.swing.BoxLayout.LINE_AXIS));

        lbl_returnOrderID.setText("Mã đơn ĐT:");
        lbl_returnOrderID.setMaximumSize(new java.awt.Dimension(80, 16));
        lbl_returnOrderID.setPreferredSize(new java.awt.Dimension(80, 16));
        pnl_returnOrderID.add(lbl_returnOrderID);

        txt_returnOrderID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        txt_returnOrderID.setMinimumSize(new java.awt.Dimension(64, 30));
        txt_returnOrderID.setPreferredSize(new java.awt.Dimension(64, 30));
        pnl_returnOrderID.add(txt_returnOrderID);

        pnl_eastReturnOrder.add(pnl_returnOrderID);

        pnl_productID.setPreferredSize(new java.awt.Dimension(462, 420));
        pnl_productID.setLayout(new java.awt.BorderLayout());

        lbl_product.setText("Sản phẩm:");
        lbl_product.setPreferredSize(new java.awt.Dimension(56, 26));
        pnl_productID.add(lbl_product, java.awt.BorderLayout.PAGE_START);

        tbl_productInfor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã SP", "Tên SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_productInfor.setMinimumSize(new java.awt.Dimension(30, 40));
        tbl_productInfor.setPreferredSize(new java.awt.Dimension(150, 40));
        tbl_productInfor.setShowGrid(true);
        scr_productInfor.setViewportView(tbl_productInfor);

        pnl_productID.add(scr_productInfor, java.awt.BorderLayout.CENTER);

        pnl_eastReturnOrder.add(pnl_productID);

        pnl_statusReturnOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnl_statusReturnOrder.setMaximumSize(new java.awt.Dimension(32833, 40));
        pnl_statusReturnOrder.setMinimumSize(new java.awt.Dimension(135, 30));
        pnl_statusReturnOrder.setPreferredSize(new java.awt.Dimension(290, 30));
        pnl_statusReturnOrder.setLayout(new javax.swing.BoxLayout(pnl_statusReturnOrder, javax.swing.BoxLayout.LINE_AXIS));

        lbl_status.setText("Trạng thái:");
        lbl_status.setPreferredSize(lbl_employeeID.getPreferredSize());
        pnl_statusReturnOrder.add(lbl_status);
        lbl_status.getAccessibleContext().setAccessibleName("Trạng thái");

        pnl_radioStatusReturnOrder.setPreferredSize(new java.awt.Dimension(219, 12));
        pnl_radioStatusReturnOrder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

        group_statusReturnOrder.add(rdb_admit);
        rdb_admit.setText("Xác nhận");
        pnl_radioStatusReturnOrder.add(rdb_admit);

        group_statusReturnOrder.add(rdb_deny);
        rdb_deny.setText("Từ chối");
        pnl_radioStatusReturnOrder.add(rdb_deny);

        pnl_statusReturnOrder.add(pnl_radioStatusReturnOrder);

        pnl_eastReturnOrder.add(pnl_statusReturnOrder);

        pnl_buttonSave.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_buttonSave.setMinimumSize(new java.awt.Dimension(72, 40));
        pnl_buttonSave.setPreferredSize(new java.awt.Dimension(300, 45));
        pnl_buttonSave.setLayout(new java.awt.BorderLayout());

        btn_saveReturnOrder.setText("Lưu");
        btn_saveReturnOrder.putClientProperty(FlatClientProperties.STYLE,""
            + "background:$Menu.background;"
            + "foreground:$Menu.foreground;");
        btn_saveReturnOrder.setPreferredSize(new java.awt.Dimension(300, 40));
        pnl_buttonSave.add(btn_saveReturnOrder, java.awt.BorderLayout.CENTER);

        pnl_eastReturnOrder.add(pnl_buttonSave);

        add(pnl_eastReturnOrder, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_saveReturnOrder;
    private javax.swing.JButton btn_searchReturnOrder;
    private javax.swing.JCheckBox chk_admitReturnOrder;
    private javax.swing.JCheckBox chk_denyReturnOrder;
    private javax.swing.JCheckBox chk_pendingReturnOrder;
    private javax.swing.JComboBox<String> cmb_typeReturnOrder;
    private javax.swing.Box.Filler filler6;
    private javax.swing.ButtonGroup group_statusReturnOrder;
    private javax.swing.JLabel lbl_employeeID;
    private javax.swing.JLabel lbl_product;
    private javax.swing.JLabel lbl_returnOrderID;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel pnl_buttonSave;
    private javax.swing.JPanel pnl_centerReturnOrder;
    private javax.swing.JPanel pnl_chkReturnOrder;
    private javax.swing.JPanel pnl_eastReturnOrder;
    private javax.swing.JPanel pnl_employeeID;
    private javax.swing.JPanel pnl_productID;
    private javax.swing.JPanel pnl_radioStatusReturnOrder;
    private javax.swing.JPanel pnl_returnOrderID;
    private javax.swing.JPanel pnl_searchRerturnOrder;
    private javax.swing.JPanel pnl_statusReturnOrder;
    private javax.swing.JPanel pnl_topReturnOrder;
    private javax.swing.JRadioButton rdb_admit;
    private javax.swing.JRadioButton rdb_deny;
    private javax.swing.JScrollPane scr_inforReturnOrder;
    private javax.swing.JScrollPane scr_productInfor;
    private javax.swing.JTable tbl_inforReturnOrder;
    private javax.swing.JTable tbl_productInfor;
    private javax.swing.JTextField txt_employeeID;
    private javax.swing.JTextField txt_returnOrderID;
    private javax.swing.JTextField txt_searchReturnOrder;
    // End of variables declaration//GEN-END:variables
}
