/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import raven.toast.Notifications;


/**
 *
 * @author Hoàng Khang
 */
public class StatementAccounting_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Statement_GUI
     */
    public StatementAccounting_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_infomation = new javax.swing.JPanel();
        pnl_cashCountInfoHeader = new javax.swing.JPanel();
        pnl_cashCountTime = new javax.swing.JPanel();
        txt_cashCountTime = new javax.swing.JTextField();
        date_cashCountTime = new com.toedter.calendar.JDateChooser();
        pnl_cashCountInfoBody = new javax.swing.JPanel();
        pnl_employeeCashCount1 = new javax.swing.JPanel();
        lbl_employeeCashCount1 = new javax.swing.JLabel();
        txt_employeeCashCount1 = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        pnl_employeeCashCount1Name = new javax.swing.JPanel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(5, 32767));
        txt_employeeCashCount1Name = new javax.swing.JTextField();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        pnl_employeeCashCount2 = new javax.swing.JPanel();
        lbl_employeeCashCount2 = new javax.swing.JLabel();
        txt_employeeCashCount2 = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        pnl_employeeCashCount2Name = new javax.swing.JPanel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(5, 32767));
        txt_employeeCashCount1Name1 = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        pnl_cashCountInfoFooter = new javax.swing.JPanel();
        pnl_cashCountTotal = new javax.swing.JPanel();
        lbl_cashCountTotal = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        txt_cashCountTotal = new javax.swing.JTextField();
        pnl_cashCountSave = new javax.swing.JPanel();
        btn_saveCashCount = new javax.swing.JButton();
        pnl_title = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        lbl_titleCashCount = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel1 = new javax.swing.JPanel();
        scr_cashCounts = new javax.swing.JScrollPane();
        tbl_cashCounts = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_infomation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        pnl_infomation.setPreferredSize(new java.awt.Dimension(300, 690));
        pnl_infomation.setLayout(new java.awt.BorderLayout());

        pnl_cashCountInfoHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 15, 1));
        pnl_cashCountInfoHeader.setLayout(new javax.swing.BoxLayout(pnl_cashCountInfoHeader, javax.swing.BoxLayout.LINE_AXIS));

        pnl_cashCountTime.setLayout(new java.awt.BorderLayout());

        txt_cashCountTime.setEditable(false);
        txt_cashCountTime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_cashCountTime.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_cashCountTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cashCountTimeActionPerformed(evt);
            }
        });
        pnl_cashCountTime.add(txt_cashCountTime, java.awt.BorderLayout.CENTER);

        pnl_cashCountInfoHeader.add(pnl_cashCountTime);

        date_cashCountTime.setDateFormatString("M d, yyyy");
        pnl_cashCountInfoHeader.add(date_cashCountTime);

        pnl_infomation.add(pnl_cashCountInfoHeader, java.awt.BorderLayout.NORTH);

        pnl_cashCountInfoBody.setLayout(new java.awt.GridLayout(10, 1));

        pnl_employeeCashCount1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        pnl_employeeCashCount1.setLayout(new javax.swing.BoxLayout(pnl_employeeCashCount1, javax.swing.BoxLayout.X_AXIS));

        lbl_employeeCashCount1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_employeeCashCount1.setText("Nhân viên 1:");
        lbl_employeeCashCount1.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_employeeCashCount1.add(lbl_employeeCashCount1);

        txt_employeeCashCount1.setEditable(false);
        txt_employeeCashCount1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount1.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount1ActionPerformed(evt);
            }
        });
        pnl_employeeCashCount1.add(txt_employeeCashCount1);
        pnl_employeeCashCount1.add(filler5);

        pnl_cashCountInfoBody.add(pnl_employeeCashCount1);

        pnl_employeeCashCount1Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        pnl_employeeCashCount1Name.setLayout(new javax.swing.BoxLayout(pnl_employeeCashCount1Name, javax.swing.BoxLayout.X_AXIS));
        pnl_employeeCashCount1Name.add(filler14);

        txt_employeeCashCount1Name.setEditable(false);
        txt_employeeCashCount1Name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount1Name.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount1NameActionPerformed(evt);
            }
        });
        pnl_employeeCashCount1Name.add(txt_employeeCashCount1Name);
        pnl_employeeCashCount1Name.add(filler16);

        pnl_cashCountInfoBody.add(pnl_employeeCashCount1Name);

        pnl_employeeCashCount2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        pnl_employeeCashCount2.setPreferredSize(new java.awt.Dimension(200, 32));
        pnl_employeeCashCount2.setLayout(new javax.swing.BoxLayout(pnl_employeeCashCount2, javax.swing.BoxLayout.LINE_AXIS));

        lbl_employeeCashCount2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_employeeCashCount2.setText("Nhân viên 2:");
        lbl_employeeCashCount2.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_employeeCashCount2.add(lbl_employeeCashCount2);

        txt_employeeCashCount2.setEditable(false);
        txt_employeeCashCount2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount2.setMinimumSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount2.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount2ActionPerformed(evt);
            }
        });
        pnl_employeeCashCount2.add(txt_employeeCashCount2);
        pnl_employeeCashCount2.add(filler6);

        pnl_cashCountInfoBody.add(pnl_employeeCashCount2);

        pnl_employeeCashCount2Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        pnl_employeeCashCount2Name.setLayout(new javax.swing.BoxLayout(pnl_employeeCashCount2Name, javax.swing.BoxLayout.X_AXIS));
        pnl_employeeCashCount2Name.add(filler15);

        txt_employeeCashCount1Name1.setEditable(false);
        txt_employeeCashCount1Name1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount1Name1.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount1Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount1Name1ActionPerformed(evt);
            }
        });
        pnl_employeeCashCount2Name.add(txt_employeeCashCount1Name1);
        pnl_employeeCashCount2Name.add(filler17);

        pnl_cashCountInfoBody.add(pnl_employeeCashCount2Name);

        pnl_infomation.add(pnl_cashCountInfoBody, java.awt.BorderLayout.CENTER);

        pnl_cashCountInfoFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        pnl_cashCountInfoFooter.setLayout(new javax.swing.BoxLayout(pnl_cashCountInfoFooter, javax.swing.BoxLayout.Y_AXIS));

        pnl_cashCountTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        pnl_cashCountTotal.setPreferredSize(new java.awt.Dimension(160, 50));
        pnl_cashCountTotal.setLayout(new javax.swing.BoxLayout(pnl_cashCountTotal, javax.swing.BoxLayout.LINE_AXIS));

        lbl_cashCountTotal.setFont(lbl_cashCountTotal.getFont().deriveFont((lbl_cashCountTotal.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, 28));
        lbl_cashCountTotal.setText("Tổng:");
        pnl_cashCountTotal.add(lbl_cashCountTotal);
        pnl_cashCountTotal.add(filler9);

        txt_cashCountTotal.setEditable(false);
        txt_cashCountTotal.setFont(txt_cashCountTotal.getFont().deriveFont((txt_cashCountTotal.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, 26));
        txt_cashCountTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_cashCountTotal.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_cashCountTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cashCountTotalActionPerformed(evt);
            }
        });
        pnl_cashCountTotal.add(txt_cashCountTotal);

        pnl_cashCountInfoFooter.add(pnl_cashCountTotal);

        pnl_cashCountSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 5, 10, 5));
        pnl_cashCountSave.setLayout(new java.awt.BorderLayout());

        btn_saveCashCount.setFont(btn_saveCashCount.getFont().deriveFont(btn_saveCashCount.getFont().getStyle() | java.awt.Font.BOLD, 20));
        btn_saveCashCount.setText("Tạo báo cáo");
        btn_saveCashCount.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        btn_saveCashCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveCashCountActionPerformed(evt);
            }
        });
        pnl_cashCountSave.add(btn_saveCashCount, java.awt.BorderLayout.PAGE_END);

        pnl_cashCountInfoFooter.add(pnl_cashCountSave);

        pnl_infomation.add(pnl_cashCountInfoFooter, java.awt.BorderLayout.SOUTH);

        add(pnl_infomation, java.awt.BorderLayout.EAST);

        pnl_title.setLayout(new java.awt.BorderLayout());
        pnl_title.add(filler10, java.awt.BorderLayout.SOUTH);

        lbl_titleCashCount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_titleCashCount.setText("Kiểm tiền");
        pnl_title.add(lbl_titleCashCount, java.awt.BorderLayout.CENTER);
        pnl_title.add(filler11, java.awt.BorderLayout.NORTH);
        pnl_title.add(filler12, java.awt.BorderLayout.LINE_START);

        add(pnl_title, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tbl_cashCounts.setFont(tbl_cashCounts.getFont().deriveFont(tbl_cashCounts.getFont().getStyle() & ~java.awt.Font.BOLD, 18));
        tbl_cashCounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "500.000", null, null},
                {"2", "200.000", null, null},
                {"3", "100.000", null, null},
                {"4", "50.000", null, null},
                {"5", "20.000", null, null},
                {"6", "10.000", null, null},
                {"7", "5.000", null, null},
                {"8", "2.000", null, null},
                {"9", "1.000", null, null},
                {"10", "500", null, null}
            },
            new String [] {
                "STT", "Mệnh giá", "Số lượng", "Tổng"
            }
        ));
        tbl_cashCounts.setRowHeight(45);
        scr_cashCounts.setViewportView(tbl_cashCounts);

        jPanel1.add(scr_cashCounts, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employeeCashCount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount1ActionPerformed

    private void txt_employeeCashCount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount2ActionPerformed

    private void txt_cashCountTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cashCountTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cashCountTimeActionPerformed

    private void txt_cashCountTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cashCountTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cashCountTotalActionPerformed

    private void txt_employeeCashCount1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount1NameActionPerformed

    private void txt_employeeCashCount1Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount1Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount1Name1ActionPerformed

    private void btn_saveCashCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveCashCountActionPerformed
        // TODO add your handling code here:
        Notifications.getInstance().show(Notifications.Type.INFO, "Tạo phiếu kiểm tiền thành công");
    }//GEN-LAST:event_btn_saveCashCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_saveCashCount;
    private com.toedter.calendar.JDateChooser date_cashCountTime;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cashCountTotal;
    private javax.swing.JLabel lbl_employeeCashCount1;
    private javax.swing.JLabel lbl_employeeCashCount2;
    private javax.swing.JLabel lbl_titleCashCount;
    private javax.swing.JPanel pnl_cashCountInfoBody;
    private javax.swing.JPanel pnl_cashCountInfoFooter;
    private javax.swing.JPanel pnl_cashCountInfoHeader;
    private javax.swing.JPanel pnl_cashCountSave;
    private javax.swing.JPanel pnl_cashCountTime;
    private javax.swing.JPanel pnl_cashCountTotal;
    private javax.swing.JPanel pnl_employeeCashCount1;
    private javax.swing.JPanel pnl_employeeCashCount1Name;
    private javax.swing.JPanel pnl_employeeCashCount2;
    private javax.swing.JPanel pnl_employeeCashCount2Name;
    private javax.swing.JPanel pnl_infomation;
    private javax.swing.JPanel pnl_title;
    private javax.swing.JScrollPane scr_cashCounts;
    private javax.swing.JTable tbl_cashCounts;
    private javax.swing.JTextField txt_cashCountTime;
    private javax.swing.JTextField txt_cashCountTotal;
    private javax.swing.JTextField txt_employeeCashCount1;
    private javax.swing.JTextField txt_employeeCashCount1Name;
    private javax.swing.JTextField txt_employeeCashCount1Name1;
    private javax.swing.JTextField txt_employeeCashCount2;
    // End of variables declaration//GEN-END:variables
}
