/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Hoàng Khang
 */
public class StatementCashCount_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Statement_GUI
     */
    public StatementCashCount_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_infomation = new javax.swing.JPanel();
        pnl_cashCountInfoHeader = new javax.swing.JPanel();
        pnl_cashCountTime = new javax.swing.JPanel();
        txt_cashCountTime = new javax.swing.JTextField();
        pnl_cashCountInfoBody = new javax.swing.JPanel();
        pnl_employeeCashCount1 = new javax.swing.JPanel();
        lbl_employeeCashCount1 = new javax.swing.JLabel();
        txt_employeeCashCount1 = new javax.swing.JTextField();
        pnl_employeeCashCount2 = new javax.swing.JPanel();
        lbl_employeeCashCount2 = new javax.swing.JLabel();
        txt_employeeCashCount2 = new javax.swing.JTextField();
        pnl_cashCountInfoFooter = new javax.swing.JPanel();
        pnl_cashCountTotal = new javax.swing.JPanel();
        lbl_cashCountTotal = new javax.swing.JLabel();
        txt_cashCountTotal = new javax.swing.JTextField();
        pnl_cashCountSave = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnl_title = new javax.swing.JPanel();
        lbl_titleCashCount = new javax.swing.JLabel();
        scr_cashCount = new javax.swing.JScrollPane();
        tbl_cashCounts = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_infomation.setLayout(new java.awt.BorderLayout());

        pnl_cashCountInfoHeader.setLayout(new javax.swing.BoxLayout(pnl_cashCountInfoHeader, javax.swing.BoxLayout.LINE_AXIS));

        pnl_cashCountTime.setLayout(new java.awt.CardLayout(3, 5));

        txt_cashCountTime.setEditable(false);
        txt_cashCountTime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_cashCountTime.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_cashCountTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cashCountTimeActionPerformed(evt);
            }
        });
        pnl_cashCountTime.add(txt_cashCountTime, "card2");

        pnl_cashCountInfoHeader.add(pnl_cashCountTime);

        pnl_infomation.add(pnl_cashCountInfoHeader, java.awt.BorderLayout.NORTH);

        pnl_cashCountInfoBody.setLayout(new java.awt.GridLayout(10, 1));

        pnl_employeeCashCount1.setLayout(new java.awt.GridBagLayout());

        lbl_employeeCashCount1.setText("Nhân viên 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 5.0;
        pnl_employeeCashCount1.add(lbl_employeeCashCount1, gridBagConstraints);

        txt_employeeCashCount1.setEditable(false);
        txt_employeeCashCount1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount1.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount1ActionPerformed(evt);
            }
        });
        pnl_employeeCashCount1.add(txt_employeeCashCount1, new java.awt.GridBagConstraints());

        pnl_cashCountInfoBody.add(pnl_employeeCashCount1);

        pnl_employeeCashCount2.setPreferredSize(new java.awt.Dimension(200, 32));
        pnl_employeeCashCount2.setLayout(new java.awt.GridBagLayout());

        lbl_employeeCashCount2.setText("Nhân viên 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 5.0;
        pnl_employeeCashCount2.add(lbl_employeeCashCount2, gridBagConstraints);

        txt_employeeCashCount2.setEditable(false);
        txt_employeeCashCount2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_employeeCashCount2.setMinimumSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount2.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_employeeCashCount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeCashCount2ActionPerformed(evt);
            }
        });
        pnl_employeeCashCount2.add(txt_employeeCashCount2, new java.awt.GridBagConstraints());

        pnl_cashCountInfoBody.add(pnl_employeeCashCount2);

        pnl_infomation.add(pnl_cashCountInfoBody, java.awt.BorderLayout.CENTER);

        pnl_cashCountInfoFooter.setLayout(new javax.swing.BoxLayout(pnl_cashCountInfoFooter, javax.swing.BoxLayout.Y_AXIS));

        pnl_cashCountTotal.setLayout(new java.awt.BorderLayout());

        lbl_cashCountTotal.setText("Tổng:");
        pnl_cashCountTotal.add(lbl_cashCountTotal, java.awt.BorderLayout.WEST);

        txt_cashCountTotal.setEditable(false);
        txt_cashCountTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_cashCountTotal.setPreferredSize(new java.awt.Dimension(100, 22));
        txt_cashCountTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cashCountTotalActionPerformed(evt);
            }
        });
        pnl_cashCountTotal.add(txt_cashCountTotal, java.awt.BorderLayout.EAST);

        pnl_cashCountInfoFooter.add(pnl_cashCountTotal);

        pnl_cashCountSave.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Save & Exit");
        pnl_cashCountSave.add(jButton1, java.awt.BorderLayout.PAGE_END);

        pnl_cashCountInfoFooter.add(pnl_cashCountSave);

        pnl_infomation.add(pnl_cashCountInfoFooter, java.awt.BorderLayout.SOUTH);

        add(pnl_infomation, java.awt.BorderLayout.LINE_END);

        pnl_title.setLayout(new java.awt.BorderLayout());

        lbl_titleCashCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titleCashCount.setText("Kiểm tiền");
        pnl_title.add(lbl_titleCashCount, java.awt.BorderLayout.CENTER);

        add(pnl_title, java.awt.BorderLayout.PAGE_START);

        tbl_cashCounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mệnh giá", "Số lượng", "Tổng"
            }
        ));
        tbl_cashCounts.setPreferredSize(new java.awt.Dimension(400, 180));
        scr_cashCount.setViewportView(tbl_cashCounts);

        add(scr_cashCount, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employeeCashCount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount1ActionPerformed

    private void txt_employeeCashCount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employeeCashCount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employeeCashCount2ActionPerformed

    private void txt_cashCountTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cashCountTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cashCountTimeActionPerformed

    private void txt_cashCountTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cashCountTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cashCountTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_cashCountTotal;
    private javax.swing.JLabel lbl_employeeCashCount1;
    private javax.swing.JLabel lbl_employeeCashCount2;
    private javax.swing.JLabel lbl_titleCashCount;
    private javax.swing.JPanel pnl_cashCountInfoBody;
    private javax.swing.JPanel pnl_cashCountInfoFooter;
    private javax.swing.JPanel pnl_cashCountInfoHeader;
    private javax.swing.JPanel pnl_cashCountSave;
    private javax.swing.JPanel pnl_cashCountTime;
    private javax.swing.JPanel pnl_cashCountTotal;
    private javax.swing.JPanel pnl_employeeCashCount1;
    private javax.swing.JPanel pnl_employeeCashCount2;
    private javax.swing.JPanel pnl_infomation;
    private javax.swing.JPanel pnl_title;
    private javax.swing.JScrollPane scr_cashCount;
    private javax.swing.JTable tbl_cashCounts;
    private javax.swing.JTextField txt_cashCountTime;
    private javax.swing.JTextField txt_cashCountTotal;
    private javax.swing.JTextField txt_employeeCashCount1;
    private javax.swing.JTextField txt_employeeCashCount2;
    // End of variables declaration//GEN-END:variables
}
