/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Hoàng Khang
 */
public class ViewCashCountSheetList_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ViewCashCountSheetList
     */
    public ViewCashCountSheetList_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_header = new javax.swing.JPanel();
        pnl_employee1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnl_employee2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        pnl_startDate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        pnl_endDate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        pnl_difference = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        pnl_sales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cashCountSheetList = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.BorderLayout());

        pnl_header.setLayout(new java.awt.GridBagLayout());

        pnl_employee1.setLayout(new javax.swing.BoxLayout(pnl_employee1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("jLabel1");
        pnl_employee1.add(jLabel1);

        jTextField1.setText("jTextField1");
        pnl_employee1.add(jTextField1);

        pnl_header.add(pnl_employee1, new java.awt.GridBagConstraints());

        pnl_employee2.setLayout(new javax.swing.BoxLayout(pnl_employee2, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("jLabel1");
        pnl_employee2.add(jLabel2);

        jTextField2.setText("jTextField1");
        pnl_employee2.add(jTextField2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        pnl_header.add(pnl_employee2, gridBagConstraints);

        pnl_startDate.setLayout(new javax.swing.BoxLayout(pnl_startDate, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("jLabel1");
        pnl_startDate.add(jLabel3);

        jTextField3.setText("jTextField1");
        pnl_startDate.add(jTextField3);

        pnl_header.add(pnl_startDate, new java.awt.GridBagConstraints());

        pnl_endDate.setLayout(new javax.swing.BoxLayout(pnl_endDate, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setText("jLabel1");
        pnl_endDate.add(jLabel4);

        jTextField4.setText("jTextField1");
        pnl_endDate.add(jTextField4);

        pnl_header.add(pnl_endDate, new java.awt.GridBagConstraints());

        pnl_difference.setLayout(new javax.swing.BoxLayout(pnl_difference, javax.swing.BoxLayout.X_AXIS));

        jLabel5.setText("jLabel1");
        pnl_difference.add(jLabel5);

        jTextField5.setText("jTextField1");
        pnl_difference.add(jTextField5);

        pnl_header.add(pnl_difference, new java.awt.GridBagConstraints());

        pnl_sales.setLayout(new javax.swing.BoxLayout(pnl_sales, javax.swing.BoxLayout.X_AXIS));

        jLabel6.setText("jLabel1");
        pnl_sales.add(jLabel6);

        jTextField6.setText("jTextField1");
        pnl_sales.add(jTextField6);

        pnl_header.add(pnl_sales, new java.awt.GridBagConstraints());

        add(pnl_header, java.awt.BorderLayout.PAGE_START);

        tbl_cashCountSheetList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_cashCountSheetList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel pnl_difference;
    private javax.swing.JPanel pnl_employee1;
    private javax.swing.JPanel pnl_employee2;
    private javax.swing.JPanel pnl_endDate;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_sales;
    private javax.swing.JPanel pnl_startDate;
    private javax.swing.JTable tbl_cashCountSheetList;
    // End of variables declaration//GEN-END:variables
}
